/**
 * Aflac Final Expense — drug list CGFLP04363, effective 09/17/2026.
 *
 * Extracted by scripts/extract-aflac-drugs.py. The list's per-product marks are
 * drawn as vector graphics rather than text, so they are recovered by rendering
 * each page and reading the marks by colour and position; see that script for
 * how rows are bounded and how the extraction was validated.
 *
 * Each row is [drug, condition, plans, page], where `plans` names the Final
 * Expense classes the medication is unacceptable for:
 *
 *   P  Preferred      S  Standard      M  Modified
 *
 * A medication marked for Preferred only still leaves Standard and Modified
 * open, which is the point of carrying the marks per plan rather than treating
 * the list as one carrier-wide decline.
 *
 * The list's Medicare supplement column is not carried here: this platform
 * quotes final expense only.
 *
 * TWO KINDS OF ROW, and they are loaded differently:
 *
 *   "Any Condition" — the medication is unacceptable for that plan whatever it
 *   was prescribed for. These load as declines.
 *
 *   A named condition — the guide is explicit that the medication is only
 *   unacceptable "when prescribed for any of the listed conditions". The health
 *   interview records which medications a client takes, not what each was
 *   prescribed for, so these cannot be decided here. They load as refer
 *   (requires underwriting verification) with the conditions named in the
 *   explanation, rather than declining a client whose Demadex is for something
 *   the list does not care about.
 */

/** [drug name, condition, plans it rules out, drug-list page] */
export type AflacDrugRule = [string, string, string, number];

export const AFLAC_DRUG_RULES: AflacDrugRule[] = [
  ['ABACAVIR', 'Any Condition', 'MPS', 3],
  ['ABACAVIR, DOLUTEGRAVIR AND LAMIVUDINE', 'Any Condition', 'MPS', 3],
  ['ABEMACICLIB', 'Any Condition', 'MPS', 3],
  ['ABIRATERONE', 'Any Condition', 'MPS', 3],
  ['ABRAXANE', 'Any Condition', 'M', 3],
  ['ABRAXANE', 'NULL', 'PS', 3],
  ['ACAMPROSATE', 'Any Condition', 'PS', 3],
  ['ACCESSPAK', 'Any Condition', 'MPS', 3],
  ['ACCUPRIL', 'Congestive heart failure', 'MPS', 3],
  ['ACEON', 'Congestive heart failure', 'MPS', 3],
  ['ACLABRUTINIB', 'Any Condition', 'MPS', 3],
  ['ACLASTA', 'Paget&apos;s disease, Cancer', 'MS', 3],
  ['ACLASTA', 'Paget&apos;s disease, cancer', 'P', 4],
  ['ACLIDINIUM', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 4],
  ['ACORAMIDIS', 'ATTR-Cardiomyopathy', 'P', 4],
  ['ACORAMIDIS', 'ATTR-Cardiomyopathy', 'S', 4],
  ['ACTIGALL', 'Any Condition', 'PS', 4],
  ['ACTINOMYCIN D', 'Any Condition', 'MPS', 4],
  ['ACTIQ', 'Cancer', 'MPS', 4],
  ['ADAGRASIB', 'Any Condition', 'MPS', 4],
  ['ADAKVEO', 'Any Condition', 'MPS', 4],
  ['ADCETRIS', 'Any Condition', 'MPS', 5],
  ['ADEFOVIR', 'Any Condition', 'PS', 5],
  ['ADRIAMYCIN', 'Any Condition', 'MPS', 5],
  ['ADRUCIL', 'Any Condition', 'MPS', 5],
  ['ADVAIR', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 5],
  ['AFEDITAB', 'Angina', 'PS', 5],
  ['AFINITOR', 'Any Condition', 'MPS', 5],
  ['AIRDUO RESPCLICK', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 5],
  ['AIROMIR', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 5],
  ['ALBUTEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 5],
  ['ALBUTEROL AND IPRATROPIUM', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 6],
  ['ALDACTONE', 'Cardiomyopathy', 'PS', 6],
  ['ALDACTONE', 'Congestive heart failure', 'MPS', 6],
  ['ALDACTONE', 'Liver or kidney disease', 'PS', 6],
  ['ALECENSA', 'Congestive heart failure', 'MPS', 6],
  ['ALECTINIB', 'Any Condition', 'MPS', 6],
  ['ALEMTUZUMAB', 'Any Condition', 'P', 6],
  ['ALEMTUZUMAB', 'Cancer', 'MS', 6],
  ['ALFERON N', 'Any Condition', 'PS', 6],
  ['ALFERON N', 'Cancer', 'M', 6],
  ['ALKABAN- AQ', 'Any Condition', 'PS', 6],
  ['ALKABAN-AQ', 'Any Condition', 'M', 6],
  ['ALKERAN', 'Any Condition', 'MPS', 6],
  ['ALTACE', 'Congestive heart failure', 'MPS', 6],
  ['ALYFTREK', 'Any Condition', 'MPS', 7],
  ['ALYGLO (IMMUNE GLOBAL INTRAVENOUS)', 'Any Condition', 'MPS', 7],
  ['ALYMSYS', 'Any Condition', 'MPS', 7],
  ['AMANTADINE', 'Parkinson disease', 'P', 7],
  ['AMEZALPAT (TPST-1120)', 'Any Condition', 'MPS', 7],
  ['AMIAS', 'Congestive heart failure', 'MPS', 7],
  ['AMINOSALICYLIC ACID', 'Any Condition', 'MPS', 7],
  ['AMIVANTAMAB', 'Any Condition', 'MPS', 7],
  ['AMLODIPINE', 'Angina', 'PS', 7],
  ['AMPYRA/ 4- AMINOPYRIDINE', 'Any Condition', 'P', 7],
  ['AMTAGVI', 'Any Condition', 'MPS', 7],
  ['ANASTROZOLE', 'Any Condition', 'MPS', 7],
  ['ANIFROLUMAB', 'Systemic Lupus Erythematosus', 'P', 7],
  ['ANKTIVA', 'Any Condition', 'MPS', 8],
  ['ANORO ELIPTA', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 8],
  ['ANTABUSE', 'Any Condition', 'PS', 8],
  ['APALUTAMIDE', 'Any Condition', 'MPS', 8],
  ['APOKYN', 'Any Condition', 'P', 8],
  ['APOMORPHINE', 'Any Condition', 'P', 8],
  ['APOMORPHINE', 'Any condition', 'S', 8],
  ['ARA-C', 'Any Condition', 'MPS', 8],
  ['ARABINOSYLCYTOSINE', 'Any Condition', 'MPS', 8],
  ['ARANESP', 'Any Condition', 'MPS', 8],
  ['AREDIA', 'Any Condition', 'MPS', 8],
  ['ARICEPT', 'Any Condition', 'MPS', 8],
  ['ARIMIDEX', 'Any Condition', 'MPS', 8],
  ['AROMASIN', 'Any Condition', 'MPS', 9],
  ['ARTANE', 'Parkinson disease', 'P', 9],
  ['ASCIMINIB', 'Any Condition', 'MPS', 9],
  ['ASPIRIN', 'Angina', 'PS', 9],
  ['ASTAGRAF XL', 'Organ transplant', 'MPS', 9],
  ['ATACAND', 'Congestive heart failure', 'MPS', 9],
  ['ATAMET', 'Parkinson disease', 'P', 9],
  ['ATENOLOL', 'Angina', 'PS', 9],
  ['ATEZOLIZUMAB', 'Any Condition', 'MPS', 10],
  ['ATROVENT', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 10],
  ['ATTRUBY', 'Cardiomyopathy', 'PS', 10],
  ['AUBAGIO', 'Any Condition', 'P', 10],
  ['AUGTYRO', 'Any Condition', 'MPS', 10],
  ['AURYXIA', 'Any Condition', 'MPS', 10],
  ['AUSTEDO', 'Any Condition', 'MPS', 10],
  ['AVAPRITINIB', 'Any Condition', 'MPS', 10],
  ['AVASTIN', 'Any Condition', 'MPS', 10],
  ['AVONEX', 'Any Condition', 'PS', 10],
  ['AVZIVI', 'Any Condition', 'MPS', 10],
  ['AXONA', 'Any Condition', 'MPS', 10],
  ['AYVAKIT', 'Any Condition', 'MPS', 11],
  ['AZACITIDINE', 'Any Condition', 'MPS', 11],
  ['AZAPIN', 'Organ transplant', 'MPS', 11],
  ['AZAPIN', 'Systemic Lupus (SLE)', 'P', 11],
  ['AZASAN', 'Organ transplant', 'MPS', 11],
  ['AZASAN', 'Systemic Lupus (SLE)', 'P', 11],
  ['AZATHIOPRINE', 'Organ transplant', 'MPS', 11],
  ['AZATHIOPRINE', 'Systemic Lupus (SLE)', 'P', 11],
  ['AZIDOTHYMIDINE (AZT)', 'Any Condition', 'MPS', 11],
  ['AZILECT', 'Parkinson disease', 'P', 11],
  ['AZIPRON', 'Parkinson&apos;s disease', 'P', 11],
  ['BACLOFEN', 'Multiple sclerosis', 'P', 11],
  ['BALVERSA', 'Any Condition', 'MPS', 11],
  ['BARACLUDE', 'Any Condition', 'PS', 11],
  ['BARICUITINIB', 'Systemic Lupus (SLE)', 'P', 12],
  ['BCG (BACILLUS CALMETTE AND GU?RIN)', 'Any Condition', 'MPS', 12],
  ['BEDAQUILINE', 'Any Condition', 'MPS', 12],
  ['BELIMUMAB', 'Any Condition', 'P', 12],
  ['BENDAMUSTINE HCI', 'Any Condition', 'MPS', 12],
  ['BENDEKA', 'Any Condition', 'MPS', 12],
  ['BENLYSTA', 'Any Condition', 'P', 12],
  ['BENZTROPINE', 'Parkinson disease', 'P', 12],
  ['BESPONSA', 'Any Condition', 'MPS', 12],
  ['BETASERON', 'Any Condition', 'P', 12],
  ['BEVACIZUMAB', 'Any Condition', 'MPS', 12],
  ['BEXAROTENE', 'Any Condition', 'MPS', 12],
  ['BGB- 16673', 'Any Condition', 'P', 12],
  ['BGB-16673', 'Any Condition', 'MS', 12],
  ['BICALUTAMIDE', 'Any Condition', 'MPS', 12],
  ['BICTEGRAVIR, EMTRICITABINE, TENOFOVIR, ALAFENAMIDE', 'Any Condition', 'MPS', 13],
  ['BIDIL', 'Any Condition', 'MPS', 13],
  ['BIKTARVY', 'Any Condition', 'MPS', 13],
  ['BIPERIDEN', 'Parkinson disease', 'P', 13],
  ['BISOPROLOL', 'Angina', 'P', 13],
  ['BISOPROLOL', 'Congestive heart failure', 'MPS', 13],
  ['BIVIGAM', 'Any Condition', 'MPS', 13],
  ['BIZENGRI', 'Any Condition', 'MPS', 13],
  ['BLENOXANE', 'Any Condition', 'MPS', 13],
  ['BLENREP', 'Any Condition', 'MPS', 13],
  ['BLEO 15K', 'Any Condition', 'MPS', 13],
  ['BLEOMYCIN', 'Any Condition', 'MPS', 13],
  ['BRENTUXIMAB VEDOTIN', 'Any Condition', 'MPS', 13],
  ['BREO ELIPTA', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 14],
  ['BREYANZI', 'Any Condition', 'MPS', 14],
  ['BRILINTA', 'Angina', 'PS', 14],
  ['BRIUMVI', 'Multiple sclerosis', 'P', 14],
  ['BROMOCRIPTINE', 'Parkinson disease', 'P', 14],
  ['BRUKINSA', 'Any Condition', 'MPS', 14],
  ['BUDESONIDE AND FORMOTEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 14],
  ['BUMETANIDE (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 14],
  ['BUMETANIDE (ANY AMOUNT)', 'Kidney Disease', 'PS', 14],
  ['BUMETANIDE (ANY AMOUNT)', 'Liver Disease', 'PS', 14],
  ['BUMEX (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 15],
  ['BUMEX (ANY AMOUNT)', 'Kidney Disease', 'PS', 15],
  ['BUMEX (ANY AMOUNT)', 'Liver Disease', 'PS', 15],
  ['BUNAVAIL', 'Any Condition', 'PS', 15],
  ['BUPRENORPHINE AND NALOXONE', 'Any Condition', 'PS', 15],
  ['BUSILVEX', 'Any Condition', 'MPS', 15],
  ['BUSULFAN', 'Any Condition', 'MPS', 15],
  ['BUSULFEX', 'Any Condition', 'MPS', 15],
  ['CABENUVA', 'Any Condition', 'MPS', 15],
  ['CABOMETYX', 'Any Condition', 'MPS', 15],
  ['CABOTEGRAVIR, RILPIVIRINE', 'Any Condition', 'MPS', 15],
  ['CABOZANTINIB', 'Any Condition', 'MPS', 15],
  ['CADUET', 'Angina', 'PS', 15],
  ['CAELYX', 'Any Condition', 'MPS', 15],
  ['CALCIFEDIOL', 'Any Condition', 'PS', 16],
  ['CALCIJEX', 'Any Condition', 'PS', 16],
  ['CALCITRIOL', 'Any Condition', 'PS', 16],
  ['CALCIUM ACETATE', 'Any Condition', 'MPS', 16],
  ['CALQUENCE', 'Any Condition', 'MPS', 16],
  ['CAMCEVI', 'Any Condition', 'MPS', 16],
  ['CAMPATH', 'Cancer', 'MPS', 16],
  ['CAMPRAL', 'Any Condition', 'PS', 16],
  ['CAMZYOS', 'Cardiomyopathy', 'PS', 16],
  ['CANDESARTAN', 'Congestive heart failure', 'MPS', 16],
  ['CAPASTAT SULFATE', 'Any Condition', 'MPS', 16],
  ['CAPECITABINE', 'Any Condition', 'MPS', 16],
  ['CAPIVASERTIB', 'Any Condition', 'MPS', 17],
  ['CAPOTEN', 'Congestive Heart Failure', 'PS', 17],
  ['CAPOTEN', 'Congestive heart failure', 'M', 17],
  ['CAPOTEN', 'Kidney disease', 'PS', 17],
  ['CAPREOMYCIN', 'Any Condition', 'MPS', 17],
  ['CAPRYLIDENE', 'Any Condition', 'MPS', 17],
  ['CAPTOPRIL', 'Congestive heart failure', 'MPS', 17],
  ['CAPTOPRIL', 'Kidney disease', 'PS', 17],
  ['CARAC', 'Any Condition', 'MPS', 17],
  ['CARBIDOPA', 'Parkinson disease', 'P', 17],
  ['CARBIDOPA, ENTACOPONE, LEVODOPA', 'Any Condition', 'P', 17],
  ['CARBIDOPA, LEVODOPA', 'Any Condition', 'P', 18],
  ['CARDICOR', 'Angina', 'PS', 18],
  ['CARDICOR', 'Congestive heart failure', 'MPS', 18],
  ['CARDIDE', 'Congestive heart failure', 'MPS', 18],
  ['CARDIZEM', 'Angina', 'PS', 18],
  ['CARDOXIN', 'Congestive heart failure', 'MPS', 18],
  ['CARDUZEN', 'Angina', 'PS', 18],
  ['CARFILZOMIB', 'Any Condition', 'MPS', 18],
  ['CAROSPIR', 'Cardiomyopathy', 'PS', 18],
  ['CAROSPIR', 'Congestive heart failure', 'MPS', 18],
  ['CAROSPIR', 'Liver or kidney disease', 'PS', 18],
  ['CARTIA', 'Angina', 'PS', 18],
  ['CARVEDILOL', 'Cardiomyopathy', 'P', 19],
  ['CARVEDILOL', 'Cardiomyopathy', 'S', 19],
  ['CARVEDILOL', 'Congestive heart failure', 'MPS', 19],
  ['CASGEVY', 'Any Condition', 'MPS', 19],
  ['CASODEX', 'Any Condition', 'MPS', 19],
  ['CATADEGBRUTINIB', 'Any Condition', 'MPS', 19],
  ['CCNU', 'Any Condition', 'MPS', 19],
  ['CEENU', 'Any Condition', 'MPS', 19],
  ['CELLCEPT', 'Organ transplant', 'MPS', 19],
  ['CELLCEPT', 'Systemic Lupus (SLE)', 'P', 19],
  ['CERESPAN', 'Angina', 'PS', 19],
  ['CERUBIDINE', 'Any Condition', 'MPS', 19],
  ['CETUXIMAB', 'Any Condition', 'MPS', 19],
  ['CHEMO IMMUNO PRESCITION INJ. (CIPI)', 'Any Condition', 'MPS', 20],
  ['CHLORAMBUCIL', 'Any Condition', 'MPS', 20],
  ['CHLORMETHINE', 'Any Condition', 'MPS', 20],
  ['CINACALCET', 'Any Condition', 'PS', 20],
  ['CISPLATIN', 'Any Condition', 'MPS', 20],
  ['CLADRIBINE', 'Any Condition', 'P', 20],
  ['CLADRIBINE', 'Cancer', 'MS', 20],
  ['CLOPIDOGREL', 'Angina', 'PS', 20],
  ['COBICISTAT', 'Any Condition', 'MPS', 20],
  ['COBICISTAT, ELVITEGRAVIR, EMTRICITABINE, AND TENOFOVIR', 'Any Condition', 'MPS', 21],
  ['COMBIVENT', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 21],
  ['COMBIVIR', 'Any Condition', 'MPS', 21],
  ['COMTAN', 'Parkinson disease', 'P', 21],
  ['CONTERGAN', 'Any Condition', 'MPS', 21],
  ['COPAXONE', 'Any Condition', 'P', 21],
  ['COPEGUS', 'Any Condition', 'PS', 21],
  ['COREG', 'Cardiomyopathy', 'PS', 21],
  ['COREG', 'Congestive heart failure', 'MPS', 21],
  ['CORLANOR', 'Angina, Cardiomyopathy', 'PS', 21],
  ['CORLANOR', 'Any Condition', 'MPS', 21],
  ['COSIBELIMAB', 'Cancer', 'S', 22],
  ['COSIBELIMAB -IPDL', 'Cancer', 'M', 22],
  ['COSIBELIMAB- IPDL', 'Cancer', 'P', 22],
  ['COSMEGEN', 'Any Condition', 'MPS', 22],
  ['COTAZYM', 'Cystic Fibrosis', 'M', 22],
  ['COUMADIN', 'Congestive heart failure', 'MPS', 22],
  ['COVERSYL', 'Congestive heart failure', 'MS', 22],
  ['COVERSYL', 'Congestive heart failure', 'P', 22],
  ['COZAAR', 'Congestive Heart Failure', 'PS', 22],
  ['COZAAR', 'Congestive heart failure', 'M', 22],
  ['COZAAR', 'Kidney disease', 'PS', 22],
  ['CREON', 'Cystic Fibrosis', 'MPS', 22],
  ['CRIXIVAN', 'Any Condition', 'MPS', 23],
  ['CRIZANLIZUMAB', 'Any Condition', 'MPS', 23],
  ['CUVPOSA', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 23],
  ['CYCLOPHOSPHAMIDE', 'Any Condition', 'MPS', 23],
  ['CYCLOSERINE', 'Any Condition', 'MPS', 23],
  ['CYCLOSET', 'Parkinson disease', 'P', 23],
  ['CYCLOSPORINE', 'Any Condition', 'MPS', 23],
  ['CYOMIA', 'Cancer', 'M', 23],
  ['CYTARABINE', 'Any Condition', 'MPS', 23],
  ['CYTOMEL', 'Any Condition', 'MPS', 23],
  ['CYTOMIA', 'Any Condition', 'MPS', 23],
  ['CYTOSAR', 'Any Condition', 'MPS', 23],
  ['CYTOSINE ARABINOSIDE', 'Any Condition', 'MPS', 23],
  ['DABRAFENIB', 'Any Condition', 'MPS', 24],
  ['DACTINOMYCIN', 'Any Condition', 'MPS', 24],
  ['DALFAMPRIDINE', 'Any Condition', 'P', 24],
  ['DANTRIUM', 'Any Condition', 'P', 24],
  ['DANTROLENE', 'Any Condition', 'P', 24],
  ['DANZITEN', 'Any Condition', 'MPS', 24],
  ['DAPAGLIFLOZIN', 'Congestive heart failure, heart failure', 'MPS', 24],
  ['DAPRODUSTAT', 'Kidney disease, kidney failure, renal insuficiency - ALL with dialysis', 'P', 24],
  ['DAPRODUSTAT', 'Kidney disease, kidney failure, renal insuficiency w/o dialysis', 'PS', 24],
  ['DAPRODUSTAT', 'Kidney disease, kidney failure, renal insuficiency with dialysis', 'S', 24],
  ['DAPRODUSTAT', 'Kidney disease, kidney failure, renal insuficiency- ALL with dialysis', 'M', 24],
  ['DARATUMUMAB', 'Any Condition', 'MPS', 24],
  ['DARBEPOETIN ALFA', 'Any Condition', 'PS', 24],
  ['DARUNAVIR', 'Any Condition', 'MPS', 24],
  ['DARZALEX', 'Any Condition', 'MPS', 24],
  ['DATOPOTAMAB DERUXTECAN/ DINK- INJ.', 'Any Condition', 'MPS', 25],
  ['DATROWAY', 'Any condition', 'P', 25],
  ['DATROWAY (INJ.)', 'Any Condition', 'MS', 25],
  ['DAUNORUBICIN', 'Any Condition', 'MPS', 25],
  ['DECADRON', 'Any Condition', 'P', 25],
  ['DEFENCATH (TAUOLIDINE AND HEPARIN)', 'Any Condition', 'MPS', 25],
  ['DEMADEX (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 25],
  ['DEMADEX (ANY AMOUNT)', 'Kidney Disease', 'S', 25],
  ['DEMADEX (ANY AMOUNT)', 'Kidney Disease, Liver disease', 'P', 25],
  ['DEMADEX (ANY AMOUNT)', 'Liver Disease', 'S', 25],
  ['DENOSUMAB-BBDZ', 'Any Condition', 'MPS', 25],
  ['DESCOVY', 'Any Condition', 'MPS', 26],
  ['DEUTETRABENZINE', 'Any Condition', 'MPS', 26],
  ['DEUTIVACAFTOR, TEZACAFTOR AND VANZACAFTOR', 'Any Condition', 'MPS', 26],
  ['DIDEOXYINOSINE', 'Any Condition', 'MPS', 26],
  ['DIGITEK', 'Cardiomyopathy', 'PS', 26],
  ['DIGITEK', 'Congestive heart failure', 'MPS', 26],
  ['DIGOX', 'Cardiomyopathy', 'PS', 26],
  ['DIGOX', 'Congestive heart failure', 'MPS', 26],
  ['DIGOXIN', 'Cardiomyopathy', 'PS', 26],
  ['DIGOXIN', 'Congestive heart failure', 'MPS', 26],
  ['DILACOR', 'Angina', 'PS', 27],
  ['DILTIA XT / XR', 'Angina', 'PS', 27],
  ['DILTIAZEM', 'Angina', 'PS', 27],
  ['DIMETHYL FUMARATE', 'Any Condition', 'P', 27],
  ['DIOVAN', 'Cardiomyopathy', 'PS', 27],
  ['DIOVAN', 'Congestive heart failure', 'MPS', 27],
  ['DIROXIMEL FUMARATE', 'Any Condition', 'P', 27],
  ['DISOPYRAMIDE', 'Cardiomyopathy', 'PS', 27],
  ['DISULFIRAM', 'Any Condition', 'PS', 27],
  ['DOCETAXEL', 'Any Condition', 'MPS', 27],
  ['DOLUTEGRAVIR', 'Any Condition', 'MPS', 28],
  ['DOLUTEGRAVIR/ RILPIRVIRINE', 'Any Condition', 'MPS', 28],
  ['DONANEMAB', 'Alzheimer&apos;s disease', 'MPS', 28],
  ['DONEPEZIL', 'Any Condition', 'MPS', 28],
  ['DONEPEZIL AND MEMANTINE', 'Any Condition', 'MPS', 28],
  ['DOPAR', 'Parkinson disease', 'P', 28],
  ['DOSTARLIMAB', 'Any Condition', 'MPS', 28],
  ['DOVATO', 'Any Condition', 'MPS', 28],
  ['DOVBLERON', 'Any Condition', 'MPS', 28],
  ['DOXERCALCIFEROL', 'Congestive heart failure', 'MPS', 28],
  ['DOXERCALCIFEROL', 'Liver or kidney disease', 'PS', 28],
  ['DOXIL', 'Any Condition', 'MPS', 28],
  ['DOXORUBICIN', 'Any Condition', 'MPS', 28],
  ['DRONABINOL', 'Cancer', 'MPS', 28],
  ['DROXIA', 'Any Condition', 'MPS', 29],
  ['DUAKLIR', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 29],
  ['DUO- NEB', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 29],
  ['DUOPA', 'Any Condition', 'P', 29],
  ['DUVYZAT', 'Any Condition', 'MPS', 29],
  ['EDARAVONE', 'Any Condition', 'MPS', 29],
  ['EDECRIN (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 29],
  ['EDECRIN (ANY AMOUNT)', 'Kidney Disease', 'PS', 29],
  ['EDECRIN (ANY AMOUNT)', 'Liver Disease', 'PS', 29],
  ['EDURANT', 'Any Condition', 'MPS', 30],
  ['EFAVIRENZ', 'Any Condition', 'MPS', 30],
  ['EFAVIRENZ, EMTRICITABINE, AND TENOFOVIR', 'Any Condition', 'MPS', 30],
  ['EFBEMALENOGRASTIM', 'Any Condition', 'P', 30],
  ['EFBEMALENOGRASTIN', 'Any Condition', 'MS', 30],
  ['EFFIENT', 'Angina', 'PS', 30],
  ['EFLORNITHINE', 'Any Condition', 'MPS', 30],
  ['EFUDEX', 'Any Condition', 'MPS', 30],
  ['ELACESTRANT', 'Cancer', 'MPS', 30],
  ['ELAFIBRANOR', 'Liver Disease', 'S', 30],
  ['ELAFIBRANOR', 'Liver disease', 'P', 30],
  ['ELAHERE', 'Any Condition', 'MPS', 30],
  ['ELBASVIR', 'Any Condition', 'PS', 30],
  ['ELBASVIR AND GRAZOPREVIR', 'Any Condition', 'PS', 30],
  ['ELDEPRYL', 'Parkinson&apos;s disease', 'P', 30],
  ['ELIGARD', 'Any Condition', 'MPS', 31],
  ['ELIPHOS', 'Any Condition', 'MPS', 31],
  ['ELIVITEGRAVIR (ALONE AND IN COMBINATION', 'Any Condition', 'MPS', 31],
  ['ELOXATIN', 'Any Condition', 'MPS', 31],
  ['ELVITEGRAVIR', 'Any Condition', 'S', 31],
  ['ELVITEGRAVIR/ COBRICISTATE/ EMBTRICITABLE/ TENOFOVIR', 'Any Condition', 'S', 31],
  ['ELVITEGRAVIR/ COBRICISTATE/ EMTRICITABINE/ TENOFOVIR', 'Any Condition', 'MP', 31],
  ['EMCYT', 'Any Condition', 'MPS', 31],
  ['EMPAGLIFLOZIN', 'Congestive heart failure, heart failure', 'M', 31],
  ['EMPAGLIFLOZIN', 'Congestive heart failure, heart failure', 'PS', 31],
  ['EMPAGLIFLOZIN', 'Kidney disease or Liver disease', 'PS', 31],
  ['EMSAM', 'Parkinson&apos;s disease', 'P', 31],
  ['EMTRICITABINE (ALONE AND IN COMBINATION)', 'Any Condition', 'MPS', 32],
  ['EMTRIVA', 'Any Condition', 'MPS', 32],
  ['ENALAPRIL', 'Congestive heart failure', 'MPS', 32],
  ['ENALAPRILAT', 'Congestive heart failure', 'MPS', 32],
  ['ENDARI', 'Any Condition', 'MPS', 32],
  ['ENHERTU', 'Any Condition', 'MPS', 32],
  ['ENOXAPARIN', 'Angina', 'PS', 32],
  ['ENSACOVE', 'Any Condition', 'MPS', 32],
  ['ENSARTINIB', 'Any Condition', 'MPS', 32],
  ['ENSIFENTRINE', 'COPD, lung disease', 'P', 32],
  ['ENTACAPONE', 'Parkinson disease', 'P', 32],
  ['ENTECAVIR', 'Any Condition', 'PS', 32],
  ['ENTRESTO', 'Congestive heart failure', 'MPS', 32],
  ['ENVARSUS', 'Any Condition', 'MPS', 33],
  ['ENZALUTAMIDE', 'Any Condition', 'MPS', 33],
  ['EPANED', 'Congestive heart failure', 'MPS', 33],
  ['EPCLUSA', 'Any Condition', 'PS', 33],
  ['EPCORITAMAB- BYSP', 'Any Condition', 'PS', 33],
  ['EPCORITAMAB-BYSP', 'Any Condition', 'M', 33],
  ['EPIVIR', 'Any Condition', 'MPS', 33],
  ['EPKINLY', 'Any Condition', 'MPS', 33],
  ['EPLERENONE', 'Cardiomyopathy', 'PS', 33],
  ['EPLERENONE', 'Congestive heart failure', 'MPS', 33],
  ['EPOETIN ALFA', 'Any Condition', 'MPS', 33],
  ['EPOGEN', 'Any Condition', 'MPS', 33],
  ['EPZICOM', 'Any Condition', 'MPS', 34],
  ['ERBITUX', 'Any Condition', 'MPS', 34],
  ['ERDAFITINIB', 'Any Condition', 'MPS', 34],
  ['ERGOLOID MESYLATES', 'Any Condition', 'MPS', 34],
  ['ERLEADA', 'Any Condition', 'MPS', 34],
  ['ERLOTINIB', 'Any Condition', 'MPS', 34],
  ['ERYTHROPOIETIN', 'Any Condition', 'MPS', 34],
  ['ESBRIET', 'Any Condition', 'MPS', 34],
  ['ESTRAMUSTINE', 'Any Condition', 'MPS', 34],
  ['ETHACRYNIC ACID (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 34],
  ['ETHACRYNIC ACID (ANY AMOUNT)', 'Kidney Disease', 'PS', 34],
  ['ETHACRYNIC ACID (ANY AMOUNT)', 'Liver Disease', 'PS', 34],
  ['ETHIONAMIDE', 'Any Condition', 'MPS', 35],
  ['ETOPOPHOS', 'Any Condition', 'MPS', 35],
  ['ETOPOSIDE', 'Any Condition', 'MPS', 35],
  ['EULEXIN', 'Any Condition', 'MPS', 35],
  ['EVEROLIMUS', 'Any Condition', 'MPS', 35],
  ['EVOMELA', 'Any Condition', 'MPS', 35],
  ['EVZIO (NALOXONE HYDROCHLORIDE', 'Any Condition', 'S', 35],
  ['EVZIO (NALOXONE HYDROCHLORIDE)', 'Any Condition', 'P', 35],
  ['EXAGAMGLOGENE AUTOTEMCEL', 'Any Condition', 'MPS', 35],
  ['EXELON', 'Alzheimer disease, dementia', 'MS', 35],
  ['EXELON', 'Any Condition', 'P', 36],
  ['EXEMESTANE', 'Any Condition', 'MPS', 36],
  ['EXFORGE', 'Any Condition', 'S', 36],
  ['EXFORGE', 'Congestive heart disease', 'M', 36],
  ['EXFORGE', 'Congestive heart faliure', 'P', 36],
  ['EXSERVAN', 'Any Condition', 'MPS', 36],
  ['EXTAVIA', 'Any Condition', 'P', 36],
  ['FAM-TRASTUZUMAB DERUXTECAN', 'Any Condition', 'P', 36],
  ['FAM-TRASTUZUMAB DERUXTECAN NXKI', 'Any Condition', 'MS', 36],
  ['FARESTON', 'Any Condition', 'MPS', 36],
  ['FARXIGA', 'Chronic kidney disease', 'P', 36],
  ['FARXIGA', 'Chronic kidney disease', 'S', 36],
  ['FARXIGA', 'Congestive heart failure, heart failure', 'MPS', 36],
  ['FASLODEX', 'Any Condition', 'MPS', 36],
  ['FEMARA', 'Any Condition', 'MPS', 37],
  ['FENCINO', 'Cancer', 'M', 37],
  ['FENSOLVI', 'Cancer', 'MPS', 37],
  ['FENTALIS', 'Cancer', 'MPS', 37],
  ['FENTANYL', 'Cancer', 'MPS', 37],
  ['FENTORA', 'Cancer', 'MPS', 37],
  ['FERRIC CITRATE', 'Any Condition', 'MPS', 37],
  ['FILGRASTIM', 'Any Condition', 'MPS', 37],
  ['FILSPARI', 'Kidney disease w/dialysis', 'MPS', 37],
  ['FILSPARI', 'Kidney disease w/o dialysis', 'PS', 37],
  ['FINERENONE', 'Any Condition', 'PS', 37],
  ['FINGOLIMOD', 'Any Condition', 'P', 37],
  ['FLEQSUVY', 'Multiple sclerosis', 'P', 38],
  ['FLOXURIDINE', 'Any Condition', 'MPS', 38],
  ['FLUOROPLEX', 'Any Condition', 'MPS', 38],
  ['FLUOROURACIL', 'Any Condition', 'MPS', 38],
  ['FLUTAMIDE', 'Any Condition', 'MPS', 38],
  ['FLUTICASONE AND SALMETEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 38],
  ['FLUTICASONE AND VILANTEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 38],
  ['FLUTICASONE, UMECLIDINIIUM AND VILANTEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 38],
  ['FOLEX PFS', 'Cancer', 'MPS', 38],
  ['FORADIL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 38],
  ['FORMOTEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 38],
  ['FOSCARNET', 'HIV/AIDS', 'M', 39],
  ['FOSCARNET', 'HIV/AIDS', 'PS', 39],
  ['FOSINOPRIL', 'Congestive heart failure', 'MPS', 39],
  ['FOSRENOL', 'Any Condition', 'MPS', 39],
  ['FOTIVDA', 'Any Condition', 'MP', 39],
  ['FOTIVDA', 'HIV/AIDS', 'S', 39],
  ['FRUQUINTINIB', 'Any Condition', 'MPS', 39],
  ['FRUZAQLA', 'Any Condition', 'MPS', 39],
  ['FUDR', 'Any Condition', 'MPS', 39],
  ['FULPHILA', 'Any condition', 'P', 39],
  ['FULPHILA', 'Cancer', 'MS', 39],
  ['FULVESTRANT', 'Any Condition', 'MPS', 39],
  ['FUROSCIX', 'Congestive heart failure', 'MPS', 39],
  ['FUROSCIX', 'Kidney disease or Liver disease', 'PS', 39],
  ['FUROSCIX (&gt;40MG)', 'Any Condition', 'P', 39],
  ['FUROSEMIDE (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 40],
  ['FUROSEMIDE (ANY AMOUNT)', 'Kidney Disease', 'PS', 40],
  ['FUROSEMIDE (ANY AMOUNT)', 'Liver Disease', 'PS', 40],
  ['FYARRO', 'Any Condition', 'MPS', 40],
  ['GABLOFEN', 'Multiple sclerosis', 'P', 40],
  ['GALANTAMINE', 'Any Condition', 'MPS', 40],
  ['GAMASTAN', 'Any Condition', 'PS', 40],
  ['GAMASTAN S/D', 'Any Condition', 'S', 40],
  ['GAMMASTAN', 'Any Condition', 'M', 40],
  ['GAVRETO', 'Any Condition', 'MPS', 41],
  ['GEDATOLISIB (FORMERLY PF-052 12384)', 'Any Condition', 'MS', 41],
  ['GEDATOLISIB (FORMERLY PF-052 12384)', 'Any condition', 'P', 41],
  ['GEFITINIB', 'Any Condition', 'MPS', 41],
  ['GEMCITABINE', 'Any Condition', 'MPS', 41],
  ['GEMTUZUMAB', 'Any Condition', 'MPS', 41],
  ['GENGRAF', 'Any Condition', 'MPS', 41],
  ['GENVOYA', 'Any Condition', 'MPS', 41],
  ['GILENYA', 'Any Condition', 'P', 41],
  ['GIVINOSTAT', 'Any Condition', 'MPS', 41],
  ['GLATIRAMER', 'Any Condition', 'P', 41],
  ['GLATIRAMER ACETATE', 'Any Condition', 'P', 41],
  ['GLATOPA', 'Any Condition', 'P', 41],
  ['GLECAPREVIR AND PIBRENTASVIR', 'Any Condition', 'PS', 41],
  ['GLEEVEC', 'Any Condition', 'MPS', 42],
  ['GLEOSTINE', 'Any Condition', 'MPS', 42],
  ['GOCOVRI', 'Any Condition', 'P', 42],
  ['GONITRO', 'Angina', 'PS', 42],
  ['GOSERELIN', 'Any Condition', 'MPS', 42],
  ['GOTISTOBART/ BNT316/ ONC-392', 'Any Condition', 'MPS', 42],
  ['GRAFAPEX', 'Any Condition', 'MPS', 42],
  ['GRANIX', 'Any Condition', 'MPS', 42],
  ['GRAZOPREVIR', 'Any Condition', 'PS', 42],
  ['HAEMATOPOIETIN HAEMOPOITEIN', 'Any Condition', 'MPS', 42],
  ['HARVONI', 'Any Condition', 'PS', 42],
  ['HECORIA', 'Any Condition', 'MPS', 43],
  ['HECTOROL', 'Any Condition', 'PS', 43],
  ['HEMANGEOL', 'Angina, Cardiomyopathy', 'PS', 43],
  ['HEPSERA', 'Liver disease', 'PS', 43],
  ['HERCEPTIN', 'Any Condition', 'MPS', 43],
  ['HERNEXEOS', 'Any Condition', 'MPS', 43],
  ['HERZUMA', 'Any Condition', 'MPS', 43],
  ['HISTRELIN', 'Any Condition', 'MPS', 43],
  ['HYDERGINE', 'Any Condition', 'MPS', 43],
  ['HYDRALAZINE AND ISOSORBIDE DINITRATE', 'Any Condition', 'MPS', 43],
  ['HYDREA', 'Any Condition', 'MPS', 43],
  ['HYDROXYCARBAMIDE', 'Any Condition', 'MPS', 44],
  ['HYDROXYCHLOROQUIN E', 'Systemic Lupus (SLE)', 'P', 44],
  ['HYDROXYUREA', 'Any Condition', 'MPS', 44],
  ['HYRNUO', 'Any Condition', 'MPS', 44],
  ['IBRANCE', 'Any Condition', 'MPS', 44],
  ['IBRUTINIB', 'Any Condition', 'MPS', 44],
  ['ICLUSIG', 'Any Condition', 'MPS', 44],
  ['ILOZYME', 'Cystic Fibrosis', 'MPS', 44],
  ['IMATINIB', 'Any Condition', 'MPS', 44],
  ['IMBRUVICA', 'Any Condition', 'MPS', 44],
  ['IMDELLTRA', 'Any Condition', 'MPS', 45],
  ['IMETELSTAT', 'Any Condition', 'MPS', 45],
  ['IMKELDI', 'Any Condition', 'MPS', 45],
  ['IMURAN', 'Organ transplant', 'MPS', 45],
  ['IMURAN', 'Systemic Lupus (SLE)', 'P', 45],
  ['INAVOLISIB', 'Any Condition', 'MPS', 45],
  ['INBRIJA', 'Any Condition', 'P', 45],
  ['INCRUSE', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 45],
  ['INDAPAMIDE', 'Congestive heart failure', 'MPS', 45],
  ['INDINAVIR', 'Any Condition', 'MPS', 45],
  ['INLEXZO', 'Any Condition', 'MP', 45],
  ['INNOVACE', 'Congestive heart failure', 'MPS', 46],
  ['INOTUZUMAB OZOGAMICIN', 'Any Condition', 'MPS', 46],
  ['INPEFA', 'Congestive heart failure, heart failure', 'MPS', 46],
  ['INSPRA', 'Cardiomyopathy', 'PS', 46],
  ['INSPRA', 'Congestive heart failure', 'MP', 46],
  ['INTERFERON ALFA N3', 'Any Condition', 'MS', 46],
  ['INTERFERON ALFA- N1', 'Cancer', 'MPS', 46],
  ['INTERFERON ALFA- N3', 'Liver disease', 'PS', 46],
  ['INTERFERON ALFA-N1', 'Cancer', 'S', 46],
  ['INTERFERON ALFA-N1', 'Liver Disease', 'S', 46],
  ['INTERFERON BETA (-1A OR -1B)', 'Multiple sclerosis', 'P', 46],
  ['INTERFERON N3', 'Any Condition', 'P', 46],
  ['INVAVOLISIB', 'Any Condition', 'S', 47],
  ['IODINE L 131', 'Any Condition', 'MPS', 47],
  ['IPRATROPIUM', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 47],
  ['IPRATROPIUM BROMIDE, ALBUTEROL SULFATE', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 47],
  ['IPRATROPIUM BROMIDE, SALBUTAMOL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 47],
  ['IQIRVO', 'Liver Disease', 'P', 47],
  ['IQIRVO', 'Liver Disease', 'S', 47],
  ['IRESSA', 'Any Condition', 'MPS', 47],
  ['IRPAGRATINIB/ ABSK- 011', 'Any Condition', 'MPS', 47],
  ['ISENTRESS', 'Any Condition', 'MPS', 47],
  ['ISOPTIN', 'Angina', 'PS', 47],
  ['ISOSORBIDE', 'Angina', 'PS', 47],
  ['ISTRADEFYLLINE', 'Any Condition', 'P', 47],
  ['ITOVEBI', 'Any Condition', 'MPS', 47],
  ['IVABRADINE', 'Cardiomyopathy, angina', 'PS', 48],
  ['IVABRADINE', 'Congestive heart failure', 'MPS', 48],
  ['IVONESCIMAB/ SMT112', 'Any Condition', 'MS', 48],
  ['IVONESCRIMAB/ SMT112', 'Any Condition', 'P', 48],
  ['IVOSIDENIB', 'Any Condition', 'MPS', 48],
  ['IWILFIN', 'Any Condition', 'MPS', 48],
  ['IXAZOMIB', 'Any Condition', 'MPS', 48],
  ['JAKAFI', 'Any Condition', 'MPS', 48],
  ['JANTOVEN', 'Congestive heart failure', 'MPS', 48],
  ['JARDIANCE', 'Chronic kidney disease', 'PS', 48],
  ['JARDIANCE', 'Congestive heart failure', 'MS', 48],
  ['JARDIANCE', 'Congestive heart failure, heart failure', 'P', 48],
  ['JAYPIRCA', 'Cancer/ lymphoma', 'MPS', 48],
  ['JELMYTO', 'Any Condition', 'MPS', 48],
  ['JEMPERLI', 'Any Condition', 'MPS', 48],
  ['JESDUVROQ', 'Kidney disease requiring dialysis', 'MPS', 49],
  ['JESDUVROQ', 'Kidney disease w/o dialysis', 'PS', 49],
  ['JULUCA (DOLUTEGRAVIR AND RILPIVIRINE)', 'Any Condition', 'MPS', 49],
  ['JYNARQUE', 'Kidney Disease', 'M', 49],
  ['JYNARQUE', 'Kidney disease', 'PS', 49],
  ['KALETRA', 'Any Condition', 'MPS', 49],
  ['KANJINTI', 'Any Condition', 'MPS', 49],
  ['KAPSPARGO', 'Angina', 'PS', 49],
  ['KAPSPARGO', 'Congestive heart failure', 'MPS', 49],
  ['KARXT (XANOMELINE AND TROPIUM)', 'Psychosis related to Alzheimer&apos;s disease', 'MPS', 49],
  ['KATERZIA', 'Angina', 'PS', 49],
  ['KEMADRIN', 'Parkinson disease', 'P', 49],
  ['KERENDIA', 'Kidney disease', 'PS', 50],
  ['KESIMPTA- CORRECTED MISSPELLED', '- Multiple sclerosis', 'P', 50],
  ['KEYTRUDA', 'Any Condition', 'MPS', 50],
  ['KISQALI', 'Any Condition', 'MPS', 50],
  ['KRAZATI', 'Any Condition', 'MPS', 50],
  ['KRYXANA', 'Any Condition', 'MPS', 50],
  ['KU-ZYME', 'Cystic Fibrosis', 'MPS', 50],
  ['KUTRASE', 'Cystic Fibrosis', 'MPS', 50],
  ['KYPROLIS', 'Any Condition', 'MPS', 50],
  ['L-PAM', 'Any Condition', 'MPS', 50],
  ['L-SARCOLYSIN', 'Any Condition', 'MPS', 50],
  ['LAMIVUDINE (ALONE AND IN COMBINATION)', 'Any Condition', 'MPS', 51],
  ['LANOXIN', 'Cardiomyopathy', 'PS', 51],
  ['LANOXIN', 'Congestive heart failure', 'MPS', 51],
  ['LANTHANUM CARBONATE', 'Any Condition', 'MPS', 51],
  ['LAPATINIB', 'Any Condition', 'MPS', 51],
  ['LARODOPA', 'Parkinson disease', 'P', 51],
  ['LASIX (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 51],
  ['LASIX (ANY AMOUNT)', 'Kidney Disease', 'PS', 51],
  ['LASIX (ANY AMOUNT)', 'Liver Disease', 'PS', 51],
  ['LAVENTAIR', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 52],
  ['LAZANDA', 'Cancer', 'MS', 52],
  ['LAZANDA', 'Cancer', 'P', 52],
  ['LECANEMAB-IRMB', 'Alzheimer&apos;s disesae', 'MPS', 52],
  ['LEDIPASVIR', 'Any Condition', 'PS', 52],
  ['LEDIPASVIR AND SOFOSBUVIR', 'Any Condition', 'PS', 52],
  ['LEMTRADA', 'Any Condition', 'P', 52],
  ['LEMTRADA', 'Cancer', 'MS', 52],
  ['LENALIDOMIDE', 'Any Condition', 'MPS', 52],
  ['LENVATINIB', 'Any Condition', 'MPS', 52],
  ['LENVIMA', 'Any Condition', 'MPS', 52],
  ['LEQEMBI', 'Alzheimer&apos;s disease', 'MPS', 52],
  ['LETROZOLE', 'Any Condition', 'MPS', 52],
  ['LEUKERAN', 'Any Condition', 'MPS', 52],
  ['LEUPROLIDE', 'Any Condition', 'MPS', 52],
  ['LEURCRISTINE', 'Any Condition', 'MPS', 53],
  ['LEVODOPA', 'Parkinson disease', 'P', 53],
  ['LIFILEUCEL', 'Any Condition', 'MPS', 53],
  ['LIFYORLI', 'Any Condition', 'MPS', 53],
  ['LINOMIDE', 'Any Condition', 'MPS', 53],
  ['LIORESAL', 'Multiple sclerosis', 'P', 53],
  ['LIPODOX', 'Any Condition', 'MPS', 53],
  ['LISINOPRIL', 'Cardiomyopathy', 'PS', 53],
  ['LISINOPRIL', 'Congestive heart failure', 'MPS', 53],
  ['LISOCABTAGENE MARALEUCE', 'Any Condition', 'MPS', 53],
  ['LNLEXZO', 'Any Condition', 'S', 53],
  ['LODOSYN', 'Parkinson disease', 'P', 53],
  ['LOMUSTINE', 'Any Condition', 'MPS', 54],
  ['LOPINAVIR AND RITONAVIR', 'Any Condition', 'MPS', 54],
  ['LOPRESSOR', 'Angina', 'PS', 54],
  ['LOPRESSOR', 'Congestive heart failure', 'MP', 54],
  ['LOPRESSOR', 'Congestive heart failure', 'S', 54],
  ['LORVACS', 'Congestive heart failure', 'MPS', 54],
  ['LOSARTAN', 'Congestive heart failure', 'MPS', 54],
  ['LOSARTAN', 'Kidney disease', 'PS', 54],
  ['LOVENOX', 'Angina', 'PS', 54],
  ['LOVOTIBEGLOGENE AUTEMCEL', 'Sickle Cell disease', 'MPS', 54],
  ['LOZOL', 'Congestive heart failure', 'MPS', 54],
  ['LUMAKRAS', 'Any Condition', 'MPS', 55],
  ['LUPRON', 'Any Condition', 'MPS', 55],
  ['LURBINECTEDIN', 'Any Condition', 'MPS', 55],
  ['LYFGENIA', 'Any Condition', 'MPS', 55],
  ['LYNPARZA', 'Any Condition', 'MPS', 55],
  ['LYSODREN', 'Any Condition', 'MPS', 55],
  ['LYVISPAH', 'Multiple sclerosis', 'P', 55],
  ['MAB THERA', 'Any Condition', 'MPS', 55],
  ['MARINOL', 'Weight Loss/Nausea/ Vomiting due to Cancer/ HIV/ AIDS', 'M', 55],
  ['MARINOL', 'Weight loss/ nausea / vomiting due to Cancer/ HIV/AIDS', 'P', 55],
  ['MARINOL', 'Weight loss/Nausea/ Vomiting due to Cancer/ HIV/ AIDS', 'S', 55],
  ['MARQIBO', 'Any Condition', 'MPS', 56],
  ['MATRIFEN', 'Cancer', 'MPS', 56],
  ['MATULANE', 'Any Condition', 'MPS', 56],
  ['MATZIM', 'Angina', 'PS', 56],
  ['MAVACAMTEN', 'Angina, Cardiomyopathy', 'S', 56],
  ['MAVACAMTEN', 'Cardiomyopathy', 'P', 56],
  ['MAVENCLAD', 'Any Condition', 'P', 56],
  ['MAVENCLAD', 'Cancer', 'MS', 56],
  ['MAVYRET', 'Any Condition', 'PS', 56],
  ['MAYZENT', 'Any Condition', 'P', 56],
  ['MECHLORETHAMINE', 'Any Condition', 'MPS', 56],
  ['MEKINIST', 'Any Condition', 'MPS', 56],
  ['MELPHALAN', 'Any Condition', 'MPS', 56],
  ['MEMANTINE', 'Any Condition', 'MPS', 56],
  ['MEMANTINE/ DONEPEZIL', 'Any Condition', 'PS', 56],
  ['MEMANTINE/DONEPEZIL', 'Any Condition', 'M', 56],
  ['MERCAPTOPURINE (6- MP)', 'Any Condition', 'MPS', 57],
  ['METHOTREXATE', 'Cancer', 'MPS', 57],
  ['METHOTREXATE', 'Organ Transplant', 'MPS', 57],
  ['METOLAZONE', 'Congestive heart failure', 'MPS', 57],
  ['METOPROLOL', 'Angina', 'PS', 57],
  ['METOPROLOL', 'Congestive heart failure', 'MPS', 57],
  ['MIRAPEX', 'Parkinson disease', 'P', 58],
  ['MIRVETUXIMAB SORAVTANSINE', 'Any Condition', 'MPS', 58],
  ['MITHRAMYCIN', 'Any Condition', 'MPS', 58],
  ['MITOMYCIN', 'Any Condition', 'MPS', 58],
  ['MITOSIL', 'Any Condition', 'MPS', 58],
  ['MITOTANE', 'Any Condition', 'MPS', 58],
  ['MITOXANTRONE', 'Any Condition', 'P', 58],
  ['MODERIBA', 'Any Condition', 'PS', 58],
  ['MONOCOR', 'Angina', 'PS', 58],
  ['MONOCOR', 'Congestive heart failure', 'MPS', 58],
  ['MUSTINE', 'Any Condition', 'MPS', 59],
  ['MUTAMYCIN', 'Any Condition', 'MPS', 59],
  ['MVASI', 'Any Condition', 'MPS', 59],
  ['MYCOBUTIN', 'Any Condition', 'MPS', 59],
  ['MYCOPHENOLATE MOFETIL', 'Organ transplant', 'MPS', 59],
  ['MYCOPHENOLATE MOFETIL', 'Systemic Lupus (SLE)', 'P', 59],
  ['MYFORTIC', 'Organ transplant', 'MPS', 59],
  ['MYFORTIC', 'Systemic Lupus (SLE)', 'P', 59],
  ['MYLERAN', 'Any Condition', 'MPS', 59],
  ['MYLOCEL', 'Any Condition', 'MPS', 59],
  ['MYLOTARG', 'Any Condition', 'MPS', 60],
  ['MYOCET', 'Any Condition', 'MPS', 60],
  ['NAB- PACLITAXEL', 'Any Condition', 'MPS', 60],
  ['NALOXONE', 'Any Condition', 'PS', 60],
  ['NALTREXONE', 'Any Condition', 'PS', 60],
  ['NAMENDA', 'Any Condition', 'MPS', 60],
  ['NAMZARIC', 'Any Condition', 'MPS', 60],
  ['NARCAN', 'Any Condition', 'PS', 60],
  ['NARSOPLIMAB', 'Any Condition', 'MPS', 60],
  ['NATALIZUMAB', 'Any Condition', 'P', 60],
  ['NATRILIX', 'Congestive heart failure', 'MPS', 60],
  ['NATULAN', 'Any Condition', 'MPS', 60],
  ['NEBUPENT', 'Pneumocystis pneumonia-PCP', 'P', 60],
  ['NELFINAVIR (ALONE AND IN COMBINATION)', 'Any Condition', 'MPS', 61],
  ['NEORAL', 'Any Condition', 'MPS', 61],
  ['NERANDOMILAST', 'Pulmonary Fibrosis, Idiopathic pulmonary Fibrosis (IPF), interstitial lung dis.', 'M', 61],
  ['NERANDOMILAST', 'Pulmonary Fibrosis, Idiopathic pulmonary fibrosis (IPF), interstitial lung dis.', 'S', 61],
  ['NERANDOMILAST', 'Pulmonary Fibrosis, Idiopathic pulmonary fibrosis (IPF), interstitial lung disease', 'P', 61],
  ['NERATINIB', 'Any Condition', 'MPS', 61],
  ['NERLYNX', 'Any Condition', 'MPS', 61],
  ['NEULASTA', 'Any Condition', 'MPS', 61],
  ['NEUPOGEN', 'Any Condition', 'MPS', 61],
  ['NEUPRO', 'Parkinson disease', 'P', 61],
  ['NIFEDIPINE', 'Angina', 'PS', 62],
  ['NILANDRON', 'Any Condition', 'MPS', 62],
  ['NILOTINIB', 'Any Condition', 'MPS', 62],
  ['NILUTAMIDE', 'Any Condition', 'MPS', 62],
  ['NINLARO', 'Any Condition', 'MPS', 62],
  ['NINTEDANIB', 'Pulmonary Fibrosis, idiopathic pulmonary fibrosis, interstitial lung disease, cancer', 'MPS', 62],
  ['NIRAPARIB', 'Any Condition', 'MPS', 62],
  ['NITRO-TIME', 'Angina', 'PS', 62],
  ['NITROGLYCERIN', 'Angina', 'PS', 62],
  ['NITROLINGUAL', 'Angina', 'PS', 62],
  ['NITROSTAT', 'Angina', 'PS', 62],
  ['NIVESTYM', 'Any Condition', 'MPS', 62],
  ['NIVOLUMAB', 'Any Condition', 'MPS', 62],
  ['NIVOLUMAB AND HYALURONIDASE-NVHY', 'Any Condition', 'MPS', 62],
  ['NORPACE', 'Cardiomyopathy', 'PS', 62],
  ['NORVASC', 'Angina', 'PS', 62],
  ['NORVIR', 'Any Condition', 'MPS', 62],
  ['NOURIANZ', 'Any Condition', 'P', 63],
  ['NOV- ONXOL', 'Any Condition', 'MPS', 63],
  ['NOVANTRONE', 'Any Condition', 'P', 63],
  ['NUPLAZID', 'Any Condition', 'P', 63],
  ['OCRELIZUMAB', 'Multiple sclerosis', 'P', 63],
  ['OCREVUS', 'Multiple sclerosis', 'P', 63],
  ['OCTREOTIDE', 'Any Condition', 'MPS', 63],
  ['OFATUMUMAB', 'Multiple sclerosis', 'P', 63],
  ['OFEV', 'Pulmonary Fibrosis, idiopathic pulmonary fibrosis (IPF), interstitial lung disease', 'MPS', 63],
  ['OFOSBUVIR AND VELPATASVIR', 'Any Condition', 'PS', 63],
  ['OGIVRI', 'Any Condition', 'MPS', 63],
  ['OHTUVAYRE', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 64],
  ['OJEMDA', 'Any Condition', 'MPS', 64],
  ['OLAPARIB', 'Any Condition', 'MPS', 64],
  ['OLODATEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 64],
  ['OLUMIANT', 'Systemic Lupus (SLE)', 'PS', 64],
  ['OMBITASVIR', 'Any Condition', 'PS', 64],
  ['OMBITASVIR, PARITAPREVIR, AND RITONAVIR', 'Any Condition', 'PS', 64],
  ['ONBREZ', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 64],
  ['ONCOVIN', 'Any Condition', 'MPS', 64],
  ['ONTRUAZANT', 'Any Condition', 'PS', 64],
  ['ONTRUZANT', 'Any Condition', 'M', 64],
  ['ONUREG', 'Any Condition', 'MPS', 64],
  ['OPDIVO', 'Any Condition', 'MPS', 65],
  ['OPDIVO QVANTIG', 'Any Condition', 'MPS', 65],
  ['ORPHENADRINE', 'Any Condition', 'P', 65],
  ['ORSERDU', 'Cancer', 'MPS', 65],
  ['OSMOLEX', 'Parkinson disease', 'P', 65],
  ['OTREXUP', 'Organ Transplant, Cancer', 'MPS', 65],
  ['OXALIPLATIN', 'Any Condition', 'MPS', 65],
  ['OXBRYTA', 'Any Condition', 'MPS', 65],
  ['OXYGEN', 'Any Condition', 'MPS', 65],
  ['OZANIMOD', 'Any Condition', 'P', 66],
  ['OZEMPIC', 'Chronic kidney disease, kidney disease', 'PS', 66],
  ['OZOBAX', 'Multiple sclerosis', 'P', 66],
  ['PACLITAXEL', 'Any Condition', 'MPS', 66],
  ['PACLITOR', 'Any Condition', 'MPS', 66],
  ['PALBOCICLIB', 'Any Condition', 'MPS', 66],
  ['PAMIDRONATE', 'Any Condition', 'MPS', 66],
  ['PANCREASE', 'Cystic Fibrosis', 'MPS', 66],
  ['PANCREAZE', 'Cystic Fibrosis', 'MPS', 66],
  ['PANCRECARB', 'Cystic Fibrosis', 'MPS', 66],
  ['PANCRELIPASE', 'Cystic Fibrosis', 'MPS', 66],
  ['PAPACON', 'Angina', 'PS', 67],
  ['PAPAVERINE', 'Angina', 'PS', 67],
  ['PAPCON', 'Angina', 'P', 67],
  ['PARCOPA', 'Parkinson disease', 'P', 67],
  ['PARICALCITOL', 'Any Condition', 'PS', 67],
  ['PARITAPREVIR', 'Any Condition', 'PS', 67],
  ['PARLODEL', 'Parkinson disease', 'P', 67],
  ['PASER', 'Any Condition', 'P', 67],
  ['PAVACOP', 'Angina', 'PS', 67],
  ['PAVAGEN', 'Angina', 'PS', 67],
  ['PEGASYS', 'Any Condition', 'PS', 67],
  ['PEGFILGRASTIM', 'Any Condition', 'MPS', 67],
  ['PEGINTERFERON ALFA- 2A', 'Any Condition', 'PS', 68],
  ['PEGINTERFERON ALFA- 2B', 'Any Condition', 'PS', 68],
  ['PEGINTERFERON ALFA- 2B', 'Cancer', 'M', 68],
  ['PEGINTERFERON BETA- 1A', 'Any Condition', 'P', 68],
  ['PEGINTRON', 'Any Condition', 'PS', 68],
  ['PELAREOREP (FORMERLY REOLYSIN)', 'Any Condition', 'MPS', 68],
  ['PEMBROLIZUMAB', 'Any Condition', 'MPS', 68],
  ['PENTAM', 'Pneumocystis jiroveci', 'P', 68],
  ['PENTAMIDINE', 'Pneumocystis jiroveci', 'P', 68],
  ['PENTOPAK', 'Angina', 'PS', 68],
  ['PENTOXIFYLLINE', 'Angina', 'PS', 68],
  ['PERINDOPRIL', 'Congestive heart failure', 'MPS', 68],
  ['PERTZYE', 'Cystic Fibrosis', 'MPS', 69],
  ['PHENADOZ', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 69],
  ['PHENERGAN', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 69],
  ['PHESGO (PERTUZUMAB/TRASTUZ UMAB/HYALURONIDASE)', 'Any Condition', 'MPS', 69],
  ['PHOSLO', 'Any Condition', 'MPS', 69],
  ['PHOSLYRA', 'Any Condition', 'MPS', 69],
  ['PIMAVANSERIN', 'Any Condition', 'P', 69],
  ['PIRFENIDONE', 'Any Condition', 'MPS', 69],
  ['PIRTOBRUTINIB', 'Cancer/lymphoma', 'MPS', 70],
  ['PLAQUENIL', 'Systemic Lupus (SLE)', 'P', 70],
  ['PLATINEX', 'Any Condition', 'MPS', 70],
  ['PLATINOL', 'Any Condition', 'MPS', 70],
  ['PLAVIX', 'Angina', 'PS', 70],
  ['PLEGRIDY', 'Any Condition', 'P', 70],
  ['PLICAMYCIN', 'Any Condition', 'MPS', 70],
  ['PONATINIB', 'Any Condition', 'MPS', 70],
  ['PRALSETINIB', 'Any Condition', 'MPS', 70],
  ['PRAMIPEXOLE', 'Parkinson disease', 'P', 70],
  ['PRASUGREL', 'Angina', 'PS', 70],
  ['PREDNISONE', 'Kidney disease', 'PS', 71],
  ['PREDNISONE', 'Systemic Lupus', 'P', 71],
  ['PRETOMANID', 'Any Condition', 'MPS', 71],
  ['PREZISTA', 'Any Condition', 'MPS', 71],
  ['PRIFTIN', 'Any Condition', 'MPS', 71],
  ['PRINIVIL', 'Congestive heart failure', 'MPS', 71],
  ['PRINVIL', 'Cardiomyopathy', 'PS', 71],
  ['PROAIR', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 71],
  ['PROCARBAZINE', 'Any Condition', 'MPS', 71],
  ['PROCARDIA', 'Angina', 'PS', 71],
  ['PROCIT', 'Cancer', 'S', 71],
  ['PROCIT', 'Kidney disease', 'S', 71],
  ['PROCRIT', 'Cancer', 'MP', 72],
  ['PROCRIT', 'Kidney disease', 'P', 72],
  ['PROCYCLIDINE', 'Parkinson disease', 'P', 72],
  ['PROGRAF', 'Any Condition', 'MPS', 72],
  ['PROLIA', 'Cancer', 'MPS', 72],
  ['PROMETHAZINE HCL (HYDROCHLORIDE)', 'Emphysema, COPD', 'P', 72],
  ['PROMETHEGAN', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 72],
  ['PROPRANOLOL', 'Angina', 'P', 72],
  ['PROPRANOLOL', 'Angina, Cardiomyopathy', 'S', 72],
  ['PROPRANOLOL', 'Cardiomyopathy', 'P', 72],
  ['PURINETHOL', 'Any Condition', 'MPS', 72],
  ['PURIXAN', 'Any Condition', 'MPS', 73],
  ['QBRELIS', 'Congestive heart failure', 'MPS', 73],
  ['QUINAPRIL', 'Congestive heart failure', 'MPS', 73],
  ['QUINEPROX', 'Systemic Lupus (SLE)', 'P', 73],
  ['RADICAVA', 'Any Condition', 'MPS', 73],
  ['RALTEGRAVIR', 'Any Condition', 'MPS', 73],
  ['RAMIPRIL', 'Congestive heart failure', 'MPS', 73],
  ['RANEXA', 'Angina', 'PS', 73],
  ['RANOLAZINE', 'Angina', 'PS', 73],
  ['RAPAMUNE', 'Any Condition', 'MPS', 73],
  ['RASAGILINE', 'Parkinson disease', 'P', 74],
  ['RASUVO', 'Any Condition', 'MPS', 74],
  ['RAWEL', 'Congestive heart failure', 'MPS', 74],
  ['RAYALDEE', 'Any Condition', 'PS', 74],
  ['RAYOS', 'Any Condition', 'PS', 74],
  ['RAZADYNE', 'Any Condition', 'MPS', 74],
  ['REBETOL', 'Any Condition', 'PS', 74],
  ['REBIF', 'Any Condition', 'P', 74],
  ['RECLAST', 'Cancer', 'MPS', 74],
  ['RECTIV', 'Angina', 'PS', 74],
  ['REGENERON CLINICAL TRIALS', 'Any Condition', 'MPS', 74],
  ['RELACORILANT', 'Any Condition', 'MPS', 74],
  ['RELEUKO', 'Any Condition', 'MPS', 75],
  ['REMESTEMCEL- L- RKND', 'Any Condition', 'S', 75],
  ['REMESTEMCEL-L-RKND', 'Any Condition', 'MP', 75],
  ['RENAGEL', 'Any Condition', 'MPS', 75],
  ['RENVELA', 'Any Condition', 'MPS', 75],
  ['REPOTRECTINIB', 'Any Condition', 'MPS', 75],
  ['RESMETIROM', 'Liver disease', 'PS', 75],
  ['RETACRIT', 'Cancer, HIV/AIDS', 'MPS', 75],
  ['RETACRIT', 'Chronic kidney disease', 'PS', 75],
  ['RETIFANLIMAB-DWLR', 'Cancer', 'MPS', 75],
  ['RETROVIR', 'Any Condition', 'MPS', 75],
  ['REVLIMID', 'Any Condition', 'MPS', 75],
  ['REZDIFFRA', 'Liver disease', 'PS', 76],
  ['RIABNI', 'Any Condition', 'MPS', 76],
  ['RIBATAB', 'Liver disease', 'PS', 76],
  ['RIBAVIRIN', 'Any Condition', 'PS', 76],
  ['RIBOCICLIB', 'Any Condition', 'MPS', 76],
  ['RIFABUTIN', 'Any Condition', 'MPS', 76],
  ['RIFAMATE', 'Any Condition', 'MPS', 76],
  ['RIFAMPIN AND ISONIAZID', 'Any Condition', 'MPS', 76],
  ['RIFAMPIN, ISONIAZID AND PYRAZINAMIDE', 'Any Condition', 'MPS', 76],
  ['RIFAPENTINE', 'Any Condition', 'MPS', 76],
  ['RIFATER', 'Any Condition', 'MPS', 76],
  ['RILPIVIRINE', 'Any Condition', 'MPS', 76],
  ['RILUTEK', 'Any Condition', 'MPS', 76],
  ['RILUZOLE', 'Any Condition', 'MPS', 76],
  ['RITONAVIR', 'Any Condition', 'MPS', 77],
  ['RITUXAN', 'Cancer', 'MPS', 77],
  ['RITUXIMAB', 'Cancer', 'MPS', 77],
  ['RIVASTIGMINE', 'Any Condition', 'MPS', 77],
  ['RIXIMYO', 'Any Condition', 'MPS', 77],
  ['ROCALTROL', 'Any Condition', 'PS', 77],
  ['ROPINIROLE', 'Parkinson disease', 'P', 77],
  ['ROQUINIMEX', 'Any Condition', 'MPS', 77],
  ['ROTIGOTINE', 'Parkinson disease', 'P', 77],
  ['RUBEX', 'Any Condition', 'MPS', 78],
  ['RUXIENCE', 'Any Condition', 'MPS', 78],
  ['RUXOLITINIB', 'Any Condition', 'MPS', 78],
  ['RYBREVANT', 'Any Condition', 'MPS', 78],
  ['RYONCIL', 'Any Condition', 'MPS', 78],
  ['RYTARY', 'Any Condition', 'P', 78],
  ['RYTELO', 'Any Condition', 'MPS', 78],
  ['RYZNEUTA', 'Any Condition', 'MPS', 78],
  ['SACUBITRIL + VALSARTAN', 'Congestive heart failure', 'MPS', 78],
  ['SAFINAMIDE', 'Any Condition', 'P', 78],
  ['SALBUTAMOL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 79],
  ['SALMETEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 79],
  ['SAMSCA', 'Congestive heart failure', 'MPS', 79],
  ['SANDIMMUNE', 'Any Condition', 'MPS', 79],
  ['SANDOSTATIN', 'Any Condition', 'MPS', 79],
  ['SANOFI', 'Multiple sclerosis', 'P', 79],
  ['SAPHNELO', 'Systemic Lupus Erythematosus', 'P', 79],
  ['SCEMBLIX', 'Any Condition', 'MPS', 79],
  ['SEBIVO', 'Liver disease', 'PS', 79],
  ['SEEBRI', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 79],
  ['SELEGILINE', 'Parkinson disease', 'P', 79],
  ['SELINEXOR', 'Any Condition', 'MPS', 80],
  ['SEMAGLUTIDE', 'Liver disease, Kidney disease', 'S', 80],
  ['SEMAGLUTIDE', 'Liver disease, kidney disease', 'P', 80],
  ['SENSIPAR', 'Any Condition', 'PS', 80],
  ['SEREVENT', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 80],
  ['SEROMYCIN', 'Any Condition', 'MPS', 80],
  ['SEVABERINIB', 'Any Condition', 'P', 80],
  ['SEVABERTINIB', 'Any Condition', 'MS', 80],
  ['SEVALAMER', 'Kidney disease w/ dialysis', 'M', 80],
  ['SEVELAMER', 'Any Condition', 'S', 80],
  ['SEVELAMER', 'Kidney disease', 'P', 80],
  ['SEVELAMER', 'Kidney disease w/ dialysis', 'P', 80],
  ['SIKLOS', 'Any Condition', 'MPS', 80],
  ['SINEMET', 'Parkinson disease', 'P', 81],
  ['SIPONIMOD', 'Any Condition', 'P', 81],
  ['SIROLIMUS', 'Any Condition', 'MPS', 81],
  ['SIRTURO', 'Any Condition', 'MPS', 81],
  ['SOAANZ', 'Congestive heart failure', 'MPS', 81],
  ['SOAANZ', 'Kidney disease, liver disease', 'PS', 81],
  ['SODIUM EDECRIN', 'Congestive heart failure', 'MPS', 81],
  ['SODIUM EDECRIN', 'Kidney disease, liver disease', 'PS', 81],
  ['SOFOSBUVIR', 'Any Condition', 'PS', 81],
  ['SOFOSBUVIR AND VELPATASVIR', 'Any Condition', 'PS', 81],
  ['SOFOSBUVIR, VELPATASVIR, AND VOXILAPREVIR', 'Any Condition', 'PS', 81],
  ['SOTAGLIFLOZIN', 'Congestive heart failure, heart failure', 'MPS', 82],
  ['SOTORASIB', 'Any Condition', 'MPS', 82],
  ['SOVALDI', 'Any Condition', 'PS', 82],
  ['SOVODAK (SOFOSBUVIR + DACLATASVIR)', 'Liver disease', 'PS', 82],
  ['SPARSENTAN', 'Dialysis, kidney failure, kidney disease', 'MPS', 82],
  ['SPARSENTAN', 'kidney failure, kidney disease', 'PS', 82],
  ['SPIOLTO RESPIMAT', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 82],
  ['SPIRIVA', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 82],
  ['SPIRONOLACTONE', 'Cardiomyopathy', 'PS', 82],
  ['SPIRONOLACTONE', 'Congestive heart failure', 'MPS', 82],
  ['SPIRONOLACTONE', 'Kidney Disease', 'PS', 83],
  ['STALEVO', 'Any Condition', 'P', 83],
  ['STIOLTO RESPIMAT', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 83],
  ['STRIBILD', 'Any Condition', 'MPS', 83],
  ['STRIVERDI', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 83],
  ['SUBLIMAZE', 'Cancer', 'MPS', 83],
  ['SUBOXONE', 'Any Condition', 'PS', 83],
  ['SUBSYS', 'Cancer', 'MPS', 83],
  ['SUCROFERRIC OXYHYDROXIDE', 'Any Condition', 'MPS', 83],
  ['SUNITINIB', 'Any Condition', 'MPS', 84],
  ['SUPPRELIN', 'Any Condition', 'MPS', 84],
  ['SUSTIVA', 'Any Condition', 'MPS', 84],
  ['SUTENT', 'Any Condition', 'MPS', 84],
  ['SYLATRON', 'Any Condition', 'PS', 84],
  ['SYMADINE', 'Parkinson&apos;s disease', 'P', 84],
  ['SYMBICORT', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 84],
  ['TABLOID', 'Any Condition', 'MPS', 84],
  ['TACROLIMUS', 'Any Condition', 'MPS', 84],
  ['TAFAMIDIS', 'Cardiomyopathy', 'P', 84],
  ['TAFAMIDIS', 'Cardiomyopathy', 'PS', 85],
  ['TAFINLAR', 'Any Condition', 'MPS', 85],
  ['TALETRECTINIB', 'Any Condition', 'MPS', 85],
  ['TALQUETAMAB', 'Any Condition', 'MPS', 85],
  ['TALVEY', 'Any Condition', 'MPS', 85],
  ['TARABINE', 'Any Condition', 'S', 85],
  ['TARABINE PFS', 'Any Condition', 'MPS', 85],
  ['TARCEVA', 'Any Condition', 'MPS', 85],
  ['TARGRETIN', 'Any Condition', 'MPS', 85],
  ['TARKA', 'Cardiomyopathy', 'PS', 85],
  ['TARKA', 'Congestive heart failure', 'MPS', 85],
  ['TARLATABMAB- DLLE', 'Any Condition', 'MPS', 85],
  ['TASCENSO ODT', 'Multiple sclerosis', 'P', 85],
  ['TASMAR', 'Any Condition', 'P', 86],
  ['TAXOTERE', 'Any Condition', 'MPS', 86],
  ['TAZTIA', 'Angina', 'PS', 86],
  ['TBO-FILGRASTIM', 'Any Condition', 'MPS', 86],
  ['TECENTRIQ', 'Any Condition', 'MPS', 86],
  ['TECFIDERA', 'Any Condition', 'P', 86],
  ['TENOFOVIR', 'Any Condition', 'MPS', 86],
  ['TENOFOVIR DISOPROXIL FUMARATE', 'Any Condition', 'MPS', 86],
  ['TENOFOVIR DISOPROXIL FUMARATE', 'Liver disease', 'P', 86],
  ['TENORMIN', 'Angina', 'PS', 86],
  ['TENSAID', 'Any Condition', 'MPS', 86],
  ['TEPADINA', 'Any Condition', 'MPS', 86],
  ['TERBUTALINE', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 87],
  ['TERIFLUNOMIDE', 'Multiple sclerosis', 'P', 87],
  ['TETRABENAZINE', 'Any Condition', 'MPS', 87],
  ['TEVIMBRA', 'Any Condition', 'MPS', 87],
  ['THALIDOMIDE', 'Any Condition', 'MPS', 87],
  ['THALOMID', 'Any Condition', 'MPS', 87],
  ['THE OPTIMIZER- NEW SMART MINI- IMPLANTABLE DEVICE DESIGNED TO IMPROVE CONTRACTION OF THE HEART', 'Congestive heart failure', 'S', 87],
  ['THE OPTIMIZER- SMART MINI-IMPLANTABLE DEVICE DESIGNED TO IMPROVE CONTRACTION OF THE HEART', 'Congestive heart failure', 'MP', 87],
  ['THIOGUANINE', 'Any Condition', 'MPS', 87],
  ['THIOPLEX', 'Any Condition', 'MPS', 87],
  ['THIOTEPA', 'Any Condition', 'MPS', 88],
  ['TIAZAC', 'Angina', 'PS', 88],
  ['TIBSOVO', 'Any Condition', 'MPS', 88],
  ['TICAGRELOR', 'Angina', 'PS', 88],
  ['TICE BCG, BCG LIVE', 'Any Condition', 'MPS', 88],
  ['TIGLUTIK', 'Any Condition', 'MPS', 88],
  ['TIOGUANNE', 'Any Condition', 'MPS', 88],
  ['TIOTROPIUM', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 88],
  ['TISLELIZUMAB-JSGR', 'Any Condition', 'MPS', 88],
  ['TIVICAY', 'Any Condition', 'MPS', 88],
  ['TIVOZANIB', 'Any Condition', 'MPS', 88],
  ['TOLAK', 'Any Condition', 'MPS', 89],
  ['TOLCAPONE', 'Any Condition', 'P', 89],
  ['TOLEBRUTINIB', 'Multiple sclerosis', 'P', 89],
  ['TOLVAPTAN', 'Congestive heart failure', 'MPS', 89],
  ['TOPOSAR', 'Any Condition', 'MPS', 89],
  ['TOPROL', 'Angina', 'PS', 89],
  ['TOPROL', 'Congestive heart failure', 'MPS', 89],
  ['TOREMIFENE', 'Any Condition', 'MPS', 89],
  ['TORSEMIDE (ANY AMOUNT)', 'Congestive heart failure', 'MPS', 89],
  ['TORSEMIDE (ANY AMOUNT)', 'Kidney Disease', 'PS', 89],
  ['TORSEMIDE (ANY AMOUNT)', 'Liver Disease', 'PS', 89],
  ['TOSITUMOMAB', 'Any Condition', 'MPS', 90],
  ['TOVORAFENIB', 'Any Condition', 'MPS', 90],
  ['TRAMETINIB', 'Any Condition', 'MPS', 90],
  ['TRANDOLAPRIL', 'Congestive heart failure', 'MPS', 90],
  ['TRASTUZUMAB', 'Any Condition', 'MPS', 90],
  ['TRAZIMERA', 'Any Condition', 'MPS', 90],
  ['TRECATOR', 'Any Condition', 'MPS', 90],
  ['TRELEGY', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 90],
  ['TRELSTAR LA', 'Any Condition', 'MPS', 90],
  ['TREOSULFAN', 'Any Condition', 'MPS', 90],
  ['TREXALL', 'Cancer', 'MPS', 90],
  ['TREXALL', 'Organ Transplant', 'MPS', 90],
  ['TRIHEXYPHENIDYL', 'Parkinson disease', 'P', 90],
  ['TRIPTODUR', 'Any Condition', 'MPS', 91],
  ['TRIPTORELIN PAMOATE', 'Any Condition', 'MPS', 91],
  ['TRITANE', 'Any Condition', 'P', 91],
  ['TRIUMEQ', 'Any Condition', 'MPS', 91],
  ['TRUQAP', 'Any Condition', 'MPS', 91],
  ['TRUVADA', 'Any Condition', 'MPS', 91],
  ['TRUXIMA', 'Any Condition', 'MPS', 91],
  ['TUCATINIB', 'Any Condition', 'MPS', 91],
  ['TUDORZA', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 91],
  ['TUKYSA', 'Any Condition', 'MPS', 91],
  ['TYBOST', 'Any Condition', 'MPS', 91],
  ['TYKERB', 'Any Condition', 'MPS', 91],
  ['TYSABRI', 'Multiple sclerosis', 'P', 91],
  ['UBLITUXIMAB', 'Multiple sclerosis', 'P', 92],
  ['UDENYCA', 'Any Condition', 'MPS', 92],
  ['UDENYCA', 'Multiple sclerosis', 'P', 92],
  ['UMECLIDINIUM', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 92],
  ['UMECLIDINIUM AND VILANTEROL', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 92],
  ['UNLOXCYT', 'Any Condition', 'MPS', 92],
  ['URSO', 'Any Condition', 'PS', 92],
  ['URSODIOL', 'Any Condition', 'PS', 92],
  ['VADADUSTAT', 'Any Condition', 'MPS', 92],
  ['VAFSEO', 'Any Condition', 'MPS', 92],
  ['VALCHOR', 'Any Condition', 'MPS', 92],
  ['VALCYTE', 'Any Condition', 'MPS', 92],
  ['VALGANCICLOVIR', 'Any Condition', 'MPS', 93],
  ['VALSARTAN', 'Cardiomyopathy', 'PS', 93],
  ['VALSARTAN', 'Congestive heart failure', 'MPS', 93],
  ['VALSARTAN + SACUBITRIL', 'Congestive heart failure', 'MPS', 93],
  ['VANTAS', 'Any Condition', 'MPS', 93],
  ['VARGATEF', 'Pulmonary Fibrosis, idiopathic pulmonary fibrosis (IPF), interstitial lung disease', 'MPS', 93],
  ['VASOTEC', 'Congestive heart failure', 'MPS', 93],
  ['VELPATASVIR', 'Liver disease', 'PS', 93],
  ['VELPHORO', 'Any Condition', 'MPS', 93],
  ['VEMLIDY', 'HIV/AIDS', 'MPS', 93],
  ['VEMLIDY', 'Liver disease', 'PS', 93],
  ['VENCLEXTA', 'Any Condition', 'MPS', 94],
  ['VENETOCLAX', 'Any Condition', 'MPS', 94],
  ['VENTOLIN', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 94],
  ['VEPDEGESTRANT/ ARV- 471', 'Any Condition', 'M', 94],
  ['VEPDEGESTRANT/ ARV- 471', 'Any Condition', 'PS', 94],
  ['VERAPAMIL', 'Angina', 'PS', 94],
  ['VERAPAMIL', 'Cardiomyopathy', 'PS', 94],
  ['VERAPAMIL', 'Congestive heart failure', 'MPS', 94],
  ['VERELAN', 'Angina', 'PS', 94],
  ['VERELAN', 'Cardiomyopathy', 'PS', 94],
  ['VERELAN', 'Congestive heart failure', 'MPS', 94],
  ['VERICIGUAT', 'Congestive heart failure, heart failure', 'MPS', 94],
  ['VERQUVO', 'Congestive heart failure, heart failure', 'MPS', 95],
  ['VERZENIO', 'Any Condition', 'MPS', 95],
  ['VIDAZA', 'Any Condition', 'MPS', 95],
  ['VINBLASTINE', 'Any Condition', 'MPS', 95],
  ['VINCREX', 'Any Condition', 'MPS', 95],
  ['VINCRISTINE', 'Any Condition', 'MPS', 95],
  ['VIOKACE', 'Cystic Fibrosis', 'MPS', 95],
  ['VIRACEPT', 'Any Condition', 'MPS', 95],
  ['VIRAZOLE', 'Any Condition', 'M', 95],
  ['VIRAZOLE', 'Liver disease', 'PS', 95],
  ['VIREAD', 'Any Condition', 'MPS', 95],
  ['VITEKTA', 'Any Condition', 'MPS', 95],
  ['VIVITROL', 'Any Condition', 'PS', 95],
  ['VOSEVI', 'Any Condition', 'PS', 95],
  ['VOXELOTOR', 'Any Condition', 'MPS', 95],
  ['VUMERITY', 'Any Condition', 'P', 96],
  ['VYNDAMAX', 'Cardiomyopathy', 'PS', 96],
  ['VYXEOS', 'Any Condition', 'MPS', 96],
  ['WARFARIN', 'Congestive heart failure', 'MPS', 96],
  ['WIXELA INHUB', 'COPD, Chronic bronchitis, emphysema, chronic respiratory condition', 'P', 96],
  ['WYOST', 'Any Condition', 'MPS', 96],
  ['XADAGO', 'Any Condition', 'P', 96],
  ['XANOMELINE AND TROPIUM', 'Psychosis related to Alzheimer&apos;s disease', 'MPS', 96],
  ['XATMEP', 'Cancer', 'MPS', 96],
  ['XATMEP', 'Organ Transplant', 'MPS', 96],
  ['XELODA', 'Any Condition', 'MPS', 97],
  ['XENAZINE', 'Any Condition', 'MPS', 97],
  ['XTANDI', 'Any Condition', 'MPS', 97],
  ['YARTEMLEA', 'Any Condition', 'MPS', 97],
  ['YONSA', 'Any Condition', 'MPS', 97],
  ['ZANUBRUTINIB', 'Any Condition', 'MPS', 97],
  ['ZAPZELCA', 'Any Condition', 'MPS', 97],
  ['ZAROXOLYN', 'Congestive heart failure', 'MPS', 97],
  ['ZARXIO', 'Any Condition', 'MPS', 97],
  ['ZEJULA', 'Any Condition', 'MPS', 97],
  ['ZELAPAR', 'Parkinson disease', 'P', 97],
  ['ZEMPLAR', 'Any Condition', 'PS', 98],
  ['ZENOCUTURZUMAB- ZBCO', 'Any Condition', 'MPS', 98],
  ['ZENPEP', 'Cystic Fibrosis', 'MPS', 98],
  ['ZEPATIER', 'Any Condition', 'PS', 98],
  ['ZEPOSIA', 'Multiple sclerosis', 'P', 98],
  ['ZEPZELCA', 'Any Condition', 'MPS', 98],
  ['ZESTRIL', 'Cardiomyopathy', 'PS', 98],
  ['ZESTRIL', 'Congestive heart failure', 'MPS', 98],
  ['ZIAGEN', 'Any Condition', 'MPS', 98],
  ['ZIDOVUDINE', 'Any Condition', 'MPS', 98],
  ['ZIDOVUDINE (ZDV + LAMIVUDINE', 'Any Condition', 'P', 98],
  ['ZIDOVUDINE (ZDV)', 'Any Condition', 'MPS', 98],
  ['ZIDOVUDINE (ZDV) + LAMIVUDINE', 'Any Condition', 'MS', 98],
  ['ZIEXTENZO', 'Any Condition', 'MPS', 98],
  ['ZIRABEV', 'Any Condition', 'MPS', 99],
  ['ZOLADEX', 'Any Condition', 'MPS', 99],
  ['ZOLDONRASIB/ RMC- 9805', 'Any Condition', 'M', 99],
  ['ZOLDONRASIB/ RMC09805', 'Any Condition', 'P', 99],
  ['ZOLDONRASIB/RMC- 9805', 'Any Condition', 'S', 99],
  ['ZOLEDRONIC ACID', 'Cancer', 'MPS', 99],
  ['ZOMETA', 'Cancer', 'MPS', 99],
  ['ZONGERINIB', 'Any Condition', 'M', 99],
  ['ZONGERTINIB', 'Any Condition', 'PS', 99],
  ['ZORTRESS', 'Any Condition', 'MPS', 99],
  ['ZUBSOLV', 'Any Condition', 'PS', 99],
  ['ZYMASE', 'Cystic Fibrosis', 'MPS', 99],
  ['ZYNYZ', 'Cancer', 'MPS', 99],
  ['ZYTIGA', 'Any Condition', 'MPS', 99],
];
