/**
 * Combined Insurance Company of America (a Chubb company) - Generational Life.
 *
 * Sources:
 *   Producer Guide      500202-R2 (EXP 03/27) - product overview p.3, annual
 *                       rates per $1,000 pp.9-11.
 *   Underwriting Guide  Generational Life - medication / rating-class table.
 *
 * Parsed programmatically from the PDFs, not hand-typed. Rate spot-checks
 * against the printed table: age 65 Preferred non-tobacco male = 68.38,
 * age 65 Graded tobacco female = 129.15, age 80 Substandard tobacco male = 511.91.
 *
 * NOTE: the rates are ANNUAL per $1,000 and the only premium mode is monthly,
 * but neither document publishes the annual-to-monthly modal factor. Until that
 * factor is supplied the rate table cannot produce a monthly premium and the
 * engine correctly reports "Rate unavailable".
 */

/** [male, female] */
export type SexPair = [number, number];
export interface ClassRates {
  nt: SexPair;
  t: SexPair;
}
export interface GenerationalLifeRateRow {
  age: number;
  preferred: ClassRates;
  standard: ClassRates;
  substandard: ClassRates;
  graded: ClassRates;
}

/** Annual rates per $1,000. Producer Guide pp.9-11. Rates are based on NEAREST age. */
export const GENERATIONAL_LIFE_RATES: GenerationalLifeRateRow[] = [
  { age: 0, preferred: { nt: [3.25, 2.89], t: [3.25, 2.89] }, standard: { nt: [4.36, 3.59], t: [4.36, 3.59] }, substandard: { nt: [4.6, 3.77], t: [4.6, 3.77] }, graded: { nt: [54.78, 38.29], t: [54.78, 38.29] } },
  { age: 1, preferred: { nt: [3.32, 2.95], t: [3.32, 2.95] }, standard: { nt: [4.42, 3.61], t: [4.42, 3.61] }, substandard: { nt: [4.66, 3.79], t: [4.66, 3.79] }, graded: { nt: [54.18, 37.03], t: [54.18, 37.03] } },
  { age: 2, preferred: { nt: [3.38, 3.03], t: [3.38, 3.03] }, standard: { nt: [4.54, 3.73], t: [4.54, 3.73] }, substandard: { nt: [4.75, 3.87], t: [4.75, 3.87] }, graded: { nt: [52.84, 36.36], t: [52.84, 36.36] } },
  { age: 3, preferred: { nt: [3.55, 3.12], t: [3.55, 3.12] }, standard: { nt: [4.68, 3.81], t: [4.68, 3.81] }, substandard: { nt: [4.93, 4], t: [4.93, 4] }, graded: { nt: [51.22, 35.67], t: [51.22, 35.67] } },
  { age: 4, preferred: { nt: [3.67, 3.26], t: [3.67, 3.26] }, standard: { nt: [4.84, 3.94], t: [4.84, 3.94] }, substandard: { nt: [5.04, 4.11], t: [5.04, 4.11] }, graded: { nt: [49.6, 34.45], t: [49.6, 34.45] } },
  { age: 5, preferred: { nt: [3.87, 3.35], t: [3.87, 3.35] }, standard: { nt: [4.96, 4.08], t: [4.96, 4.08] }, substandard: { nt: [5.21, 4.22], t: [5.21, 4.22] }, graded: { nt: [47.91, 33.24], t: [47.91, 33.24] } },
  { age: 6, preferred: { nt: [4, 3.51], t: [4, 3.51] }, standard: { nt: [5.11, 4.2], t: [5.11, 4.2] }, substandard: { nt: [5.39, 4.37], t: [5.39, 4.37] }, graded: { nt: [46.57, 32.35], t: [46.57, 32.35] } },
  { age: 7, preferred: { nt: [4.17, 3.69], t: [4.17, 3.69] }, standard: { nt: [5.33, 4.34], t: [5.33, 4.34] }, substandard: { nt: [5.52, 4.51], t: [5.52, 4.51] }, graded: { nt: [44.98, 31.67], t: [44.98, 31.67] } },
  { age: 8, preferred: { nt: [4.34, 3.82], t: [4.34, 3.82] }, standard: { nt: [5.5, 4.46], t: [5.5, 4.46] }, substandard: { nt: [5.64, 4.65], t: [5.64, 4.65] }, graded: { nt: [43.37, 30.84], t: [43.37, 30.84] } },
  { age: 9, preferred: { nt: [4.58, 3.99], t: [4.58, 3.99] }, standard: { nt: [5.72, 4.61], t: [5.72, 4.61] }, substandard: { nt: [6.01, 4.79], t: [6.01, 4.79] }, graded: { nt: [42.13, 29.36], t: [42.13, 29.36] } },
  { age: 10, preferred: { nt: [4.72, 4.19], t: [4.72, 4.19] }, standard: { nt: [5.97, 4.79], t: [5.97, 4.79] }, substandard: { nt: [6.32, 5], t: [6.32, 5] }, graded: { nt: [39.91, 28.03], t: [39.91, 28.03] } },
  { age: 11, preferred: { nt: [4.96, 4.4], t: [4.96, 4.4] }, standard: { nt: [6.28, 5.03], t: [6.28, 5.03] }, substandard: { nt: [6.76, 5.23], t: [6.76, 5.23] }, graded: { nt: [38.09, 27], t: [38.09, 27] } },
  { age: 12, preferred: { nt: [5.18, 4.62], t: [5.18, 4.62] }, standard: { nt: [6.57, 5.26], t: [6.57, 5.26] }, substandard: { nt: [7.14, 5.48], t: [7.14, 5.48] }, graded: { nt: [36.35, 25.7], t: [36.35, 25.7] } },
  { age: 13, preferred: { nt: [5.42, 4.82], t: [5.42, 4.82] }, standard: { nt: [7, 5.5], t: [7, 5.5] }, substandard: { nt: [7.62, 5.71], t: [7.62, 5.71] }, graded: { nt: [34.83, 24.89], t: [34.83, 24.89] } },
  { age: 14, preferred: { nt: [5.77, 5.04], t: [5.77, 5.04] }, standard: { nt: [7.32, 5.79], t: [7.32, 5.79] }, substandard: { nt: [8.04, 5.96], t: [8.04, 5.96] }, graded: { nt: [33.39, 23.78], t: [33.39, 23.78] } },
  { age: 15, preferred: { nt: [6.03, 5.29], t: [6.03, 5.29] }, standard: { nt: [7.61, 6.05], t: [7.61, 6.05] }, substandard: { nt: [8.53, 6.23], t: [8.53, 6.23] }, graded: { nt: [32.24, 23.09], t: [32.24, 23.09] } },
  { age: 16, preferred: { nt: [6.32, 5.56], t: [6.32, 5.56] }, standard: { nt: [7.98, 6.35], t: [7.98, 6.35] }, substandard: { nt: [8.92, 6.54], t: [8.92, 6.54] }, graded: { nt: [31.08, 22.46], t: [31.08, 22.46] } },
  { age: 17, preferred: { nt: [6.61, 5.83], t: [6.61, 5.83] }, standard: { nt: [8.37, 6.65], t: [8.37, 6.65] }, substandard: { nt: [9.28, 6.83], t: [9.28, 6.83] }, graded: { nt: [30.21, 21.76], t: [30.21, 21.76] } },
  { age: 18, preferred: { nt: [7.05, 6.08], t: [8.82, 6.97] }, standard: { nt: [8.59, 6.88], t: [11.25, 9] }, substandard: { nt: [9.44, 7.14], t: [12.78, 9.93] }, graded: { nt: [27.83, 19.52], t: [38.96, 30.52] } },
  { age: 19, preferred: { nt: [7.21, 6.36], t: [9.44, 7.41] }, standard: { nt: [8.97, 7.17], t: [12.04, 9.42] }, substandard: { nt: [9.84, 7.45], t: [13.48, 10.4] }, graded: { nt: [27.34, 19.5], t: [39.68, 30.8] } },
  { age: 20, preferred: { nt: [7.54, 6.61], t: [9.74, 7.71] }, standard: { nt: [9.32, 7.47], t: [12.59, 9.88] }, substandard: { nt: [10.2, 7.76], t: [14.08, 10.9] }, graded: { nt: [27.09, 19.28], t: [39.95, 31.07] } },
  { age: 21, preferred: { nt: [7.9, 6.94], t: [10.11, 8.1] }, standard: { nt: [9.59, 7.86], t: [13.04, 10.31] }, substandard: { nt: [10.63, 8.16], t: [14.72, 11.4] }, graded: { nt: [26.83, 19.37], t: [40.41, 31.33] } },
  { age: 22, preferred: { nt: [8.13, 7.28], t: [10.59, 8.49] }, standard: { nt: [10.04, 8.23], t: [13.73, 10.75] }, substandard: { nt: [11, 8.57], t: [15.5, 11.88] }, graded: { nt: [26.84, 19.38], t: [41.2, 31.75] } },
  { age: 23, preferred: { nt: [8.5, 7.62], t: [11.07, 8.93] }, standard: { nt: [10.5, 8.62], t: [14.43, 11.29] }, substandard: { nt: [11.39, 8.97], t: [16.27, 12.48] }, graded: { nt: [26.89, 19.47], t: [42, 31.89] } },
  { age: 24, preferred: { nt: [8.86, 7.95], t: [11.55, 9.33] }, standard: { nt: [10.96, 9], t: [15.12, 11.85] }, substandard: { nt: [11.84, 9.34], t: [17.01, 13.09] }, graded: { nt: [26.95, 19.75], t: [42.79, 32] } },
  { age: 25, preferred: { nt: [9.22, 8.27], t: [12.04, 9.84] }, standard: { nt: [11.43, 9.35], t: [15.81, 12.5] }, substandard: { nt: [12.23, 9.72], t: [17.81, 13.96] }, graded: { nt: [27.01, 19.9], t: [44.27, 32.76] } },
  { age: 26, preferred: { nt: [9.69, 8.69], t: [12.51, 10.32] }, standard: { nt: [12, 9.82], t: [16.7, 13.2] }, substandard: { nt: [12.71, 10.21], t: [18.6, 14.72] }, graded: { nt: [27.51, 20.18], t: [45.58, 33.99] } },
  { age: 27, preferred: { nt: [10.15, 9.1], t: [12.98, 10.82] }, standard: { nt: [12.32, 10.29], t: [17.42, 13.9] }, substandard: { nt: [13.3, 10.71], t: [19.61, 15.51] }, graded: { nt: [28.05, 20.42], t: [46.92, 35.54] } },
  { age: 28, preferred: { nt: [10.48, 9.53], t: [13.72, 11.42] }, standard: { nt: [12.87, 10.76], t: [18.3, 14.76] }, substandard: { nt: [13.63, 11.19], t: [20.6, 16.46] }, graded: { nt: [28.53, 20.81], t: [48.97, 36.94] } },
  { age: 29, preferred: { nt: [11.07, 9.96], t: [14.31, 12.05] }, standard: { nt: [13.44, 11.23], t: [19.36, 15.61] }, substandard: { nt: [14.22, 11.68], t: [21.8, 17.43] }, graded: { nt: [29.1, 21.19], t: [51.1, 38.18] } },
  { age: 30, preferred: { nt: [11.52, 10.44], t: [15.06, 12.69] }, standard: { nt: [14.01, 11.81], t: [20.23, 16.66] }, substandard: { nt: [14.84, 12.39], t: [23, 18.57] }, graded: { nt: [29.73, 21.82], t: [53.79, 39.52] } },
  { age: 31, preferred: { nt: [12.08, 10.97], t: [15.81, 13.31] }, standard: { nt: [14.7, 12.39], t: [21.38, 17.73] }, substandard: { nt: [15.56, 13.01], t: [24.34, 19.78] }, graded: { nt: [30.56, 22.4], t: [55.95, 40.68] } },
  { age: 32, preferred: { nt: [12.67, 11.48], t: [16.57, 14.1] }, standard: { nt: [15.41, 12.98], t: [22.97, 18.65] }, substandard: { nt: [16.31, 13.64], t: [25.95, 20.99] }, graded: { nt: [31.43, 23], t: [58.1, 42.52] } },
  { age: 33, preferred: { nt: [13.23, 12.12], t: [17.68, 14.89] }, standard: { nt: [16.11, 13.57], t: [24.12, 19.96] }, substandard: { nt: [17.05, 14.24], t: [27.51, 22.69] }, graded: { nt: [32.59, 23.65], t: [60.88, 44.14] } },
  { age: 34, preferred: { nt: [13.8, 12.65], t: [18.45, 15.71] }, standard: { nt: [16.81, 14.44], t: [25.78, 20.89] }, substandard: { nt: [17.81, 15.02], t: [29.15, 24.17] }, graded: { nt: [33.47, 24.48], t: [64.29, 45.91] } },
  { age: 35, preferred: { nt: [14.4, 13.2], t: [19.22, 16.5] }, standard: { nt: [17.51, 15.05], t: [27.47, 22.25] }, substandard: { nt: [18.91, 15.64], t: [31.3, 25.8] }, graded: { nt: [34.6, 25.05], t: [67.18, 48.22] } },
  { age: 36, preferred: { nt: [15.58, 13.85], t: [20.38, 17.49] }, standard: { nt: [18.39, 15.8], t: [28.85, 23.84] }, substandard: { nt: [19.86, 16.42], t: [33.21, 27.62] }, graded: { nt: [35.67, 25.9], t: [69.85, 50.46] } },
  { age: 37, preferred: { nt: [16.2, 14.52], t: [21.53, 18.48] }, standard: { nt: [19.66, 16.54], t: [30.81, 25.47] }, substandard: { nt: [20.82, 17.2], t: [35.76, 29.46] }, graded: { nt: [37.16, 26.83], t: [73.24, 52.04] } },
  { age: 38, preferred: { nt: [16.93, 15.32], t: [23.38, 19.45] }, standard: { nt: [20.56, 17.29], t: [32.8, 27.16] }, substandard: { nt: [22.2, 17.98], t: [38.47, 31.37] }, graded: { nt: [38.52, 27.43], t: [76.69, 54.32] } },
  { age: 39, preferred: { nt: [18.18, 15.98], t: [24.56, 20.65] }, standard: { nt: [21.44, 18.04], t: [35.5, 28.32] }, substandard: { nt: [23.16, 18.76], t: [41.27, 33.35] }, graded: { nt: [40.03, 28.42], t: [80.17, 56.01] } },
  { age: 40, preferred: { nt: [18.77, 16.82], t: [25.74, 21.67] }, standard: { nt: [22.11, 18.43], t: [37.64, 30.04] }, substandard: { nt: [24.42, 19.56], t: [44.52, 35.27] }, graded: { nt: [41.37, 29], t: [84.56, 58.3] } },
  { age: 41, preferred: { nt: [19.7, 17.67], t: [27.28, 22.96] }, standard: { nt: [23.21, 19.35], t: [40.32, 31.55] }, substandard: { nt: [26.16, 20.52], t: [47.6, 37.19] }, graded: { nt: [42.8, 29.87], t: [88.77, 60.56] } },
  { age: 42, preferred: { nt: [21.27, 18.52], t: [28.83, 24.01] }, standard: { nt: [24.8, 20.27], t: [42.98, 33.66] }, substandard: { nt: [27.41, 21.51], t: [51.41, 39.39] }, graded: { nt: [43.79, 30.73], t: [92.23, 62.32] } },
  { age: 43, preferred: { nt: [22, 19.37], t: [30.68, 25.3] }, standard: { nt: [25.94, 21.19], t: [46.62, 35.9] }, substandard: { nt: [29.24, 22.48], t: [55.28, 41.97] }, graded: { nt: [45.42, 31.57], t: [96.7, 63.84] } },
  { age: 44, preferred: { nt: [23.65, 20.42], t: [32.23, 26.6] }, standard: { nt: [27.04, 22.11], t: [49.59, 37.38] }, substandard: { nt: [30.79, 23.46], t: [59.37, 44.14] }, graded: { nt: [46.76, 32.05], t: [98.38, 66] } },
  { age: 45, preferred: { nt: [24.42, 20.83], t: [35.13, 28.16] }, standard: { nt: [28.71, 23.04], t: [52.8, 39.72] }, substandard: { nt: [32.35, 24.45], t: [63.83, 46.6] }, graded: { nt: [48.81, 33.15], t: [103.14, 67.89] } },
  { age: 46, preferred: { nt: [26.43, 21.86], t: [37.24, 29.55] }, standard: { nt: [30.21, 24.22], t: [56.25, 41.76] }, substandard: { nt: [34.1, 25.7], t: [67.94, 49] }, graded: { nt: [50.37, 34], t: [108.25, 69.38] } },
  { age: 47, preferred: { nt: [27.4, 22.9], t: [38.98, 30.91] }, standard: { nt: [31.69, 25.47], t: [59.94, 43.88] }, substandard: { nt: [35.92, 27.01], t: [72.74, 51.57] }, graded: { nt: [51.63, 34.79], t: [113.49, 71.25] } },
  { age: 48, preferred: { nt: [28.64, 24.16], t: [41.06, 32.56] }, standard: { nt: [33.19, 26.22], t: [63.59, 46.01] }, substandard: { nt: [37.8, 28.37], t: [77.79, 54.29] }, graded: { nt: [53.38, 35.52], t: [117.76, 72.69] } },
  { age: 49, preferred: { nt: [30.82, 25.22], t: [43.15, 34.22] }, standard: { nt: [35.35, 27.58], t: [66.15, 48.85] }, substandard: { nt: [39.77, 29.54], t: [83, 57.33] }, graded: { nt: [54.66, 36.62], t: [123.28, 74.35] } },
  { age: 50, preferred: { nt: [32.72, 26.28], t: [45.69, 35.89] }, standard: { nt: [36.87, 29], t: [67.78, 50.85] }, substandard: { nt: [41.91, 31.07], t: [88, 59.87] }, graded: { nt: [56.94, 37.89], t: [127.75, 76.99] } },
  { age: 51, preferred: { nt: [33.66, 27.59], t: [48.07, 37.67] }, standard: { nt: [38.63, 30.17], t: [72.61, 53.2] }, substandard: { nt: [43.92, 32.65], t: [92.27, 63.09] }, graded: { nt: [58.46, 38.79], t: [131.51, 78.72] } },
  { age: 52, preferred: { nt: [35.59, 28.87], t: [50.48, 39.46] }, standard: { nt: [40.39, 31.64], t: [76, 56.19] }, substandard: { nt: [46.14, 33.54], t: [97.09, 65.82] }, graded: { nt: [59.61, 39.68], t: [134, 80.44] } },
  { age: 53, preferred: { nt: [37.51, 30.43], t: [53.41, 41.26] }, standard: { nt: [42.14, 33.08], t: [79.48, 58.66] }, substandard: { nt: [48.34, 35.81], t: [102.7, 69.54] }, graded: { nt: [61.04, 40.88], t: [137.56, 82.87] } },
  { age: 54, preferred: { nt: [39.37, 31.99], t: [55.83, 43.04] }, standard: { nt: [43.93, 34.57], t: [84.62, 61.24] }, substandard: { nt: [50.59, 37.4], t: [108.73, 73.36] }, graded: { nt: [63.03, 42.75], t: [141.34, 85.27] } },
  { age: 55, preferred: { nt: [41.28, 33.5], t: [58.28, 44.86] }, standard: { nt: [46.54, 36.02], t: [87.87, 61.87] }, substandard: { nt: [52.81, 38.98], t: [114.03, 77.32] }, graded: { nt: [65, 44.2], t: [145.15, 88.61] } },
  { age: 56, preferred: { nt: [43.74, 35.16], t: [61.18, 47.11] }, standard: { nt: [48.63, 37.72], t: [92.21, 64.8] }, substandard: { nt: [55.55, 40.83], t: [120.2, 80.94] }, graded: { nt: [66.29, 45.97], t: [148, 91.02] } },
  { age: 57, preferred: { nt: [46.72, 36.79], t: [64.09, 49.34] }, standard: { nt: [50.6, 39.81], t: [96.15, 67.73] }, substandard: { nt: [57.69, 42.67], t: [124.84, 84.07] }, graded: { nt: [69.1, 47.42], t: [150.72, 93.96] } },
  { age: 58, preferred: { nt: [49.23, 38.75], t: [66.99, 51.58] }, standard: { nt: [53.48, 41.54], t: [101.96, 72.05] }, substandard: { nt: [60.97, 44.51], t: [132.01, 89.41] }, graded: { nt: [70.76, 49.21], t: [155.28, 97.73] } },
  { age: 59, preferred: { nt: [51.23, 40.72], t: [69.91, 53.85] }, standard: { nt: [55.3, 43.27], t: [107.56, 74.87] }, substandard: { nt: [63.68, 46.46], t: [139.18, 93.73] }, graded: { nt: [72.81, 51.38], t: [157.61, 100.34] } },
  { age: 60, preferred: { nt: [53.65, 42.71], t: [74.28, 56.07] }, standard: { nt: [58.12, 45.91], t: [113.53, 79.57] }, substandard: { nt: [66.34, 48.7], t: [145.51, 97.51] }, graded: { nt: [75.3, 54.24], t: [161.82, 104.37] } },
  { age: 61, preferred: { nt: [57.48, 45.27], t: [77.7, 58.5] }, standard: { nt: [61.55, 48.41], t: [117.59, 82.35] }, substandard: { nt: [69.96, 51.07], t: [152.64, 102.08] }, graded: { nt: [77.96, 56.45], t: [165.11, 108.28] } },
  { age: 62, preferred: { nt: [58.92, 47.33], t: [81.11, 60.97] }, standard: { nt: [63.75, 50.95], t: [121.81, 86.66] }, substandard: { nt: [72.88, 53.7], t: [159.03, 106.39] }, graded: { nt: [81.28, 58.34], t: [173.33, 110.76] } },
  { age: 63, preferred: { nt: [62.06, 49.87], t: [84.53, 63.46] }, standard: { nt: [67.12, 53.5], t: [127.99, 90.96] }, substandard: { nt: [77.16, 56.92], t: [167.67, 112.69] }, graded: { nt: [85, 60.75], t: [174.72, 117.25] } },
  { age: 64, preferred: { nt: [65.2, 52.41], t: [87.95, 66.02] }, standard: { nt: [70.51, 56.04], t: [136.86, 97.2] }, substandard: { nt: [80.77, 60.2], t: [176.91, 118.38] }, graded: { nt: [87.78, 64.53], t: [184.34, 123.39] } },
  { age: 65, preferred: { nt: [68.38, 54.95], t: [91.35, 69.28] }, standard: { nt: [75.31, 58.56], t: [140.33, 100.59] }, substandard: { nt: [85.05, 63.48], t: [185.68, 124.01] }, graded: { nt: [91.94, 67.53], t: [193.47, 129.15] } },
  { age: 66, preferred: { nt: [71.81, 58.28], t: [95.93, 72.75] }, standard: { nt: [78.91, 62.4], t: [152.59, 105.88] }, substandard: { nt: [89.63, 66.42], t: [193.48, 129.43] }, graded: { nt: [97.25, 71.52], t: [201.76, 134.88] } },
  { age: 67, preferred: { nt: [75.99, 61.06], t: [98.52, 75.45] }, standard: { nt: [83.94, 66.23], t: [162.81, 109.29] }, substandard: { nt: [94.76, 70.24], t: [200.39, 135.3] }, graded: { nt: [102.01, 75.61], t: [208.63, 142.01] } },
  { age: 68, preferred: { nt: [80.17, 63.82], t: [105.05, 79.68] }, standard: { nt: [89.02, 70.04], t: [172.48, 118.62] }, substandard: { nt: [101.65, 74.9], t: [216.38, 145.28] }, graded: { nt: [107.6, 79.66], t: [225.25, 151] } },
  { age: 69, preferred: { nt: [84.48, 67.26], t: [109.62, 83.14] }, standard: { nt: [94.06, 75.31], t: [185.02, 126.62] }, substandard: { nt: [109.73, 80.38], t: [231.05, 154.99] }, graded: { nt: [113.85, 84.98], t: [240.62, 161.09] } },
  { age: 70, preferred: { nt: [88.89, 71.47], t: [114.93, 86.61] }, standard: { nt: [101.07, 80.02], t: [195.57, 133.07] }, substandard: { nt: [116.6, 86.84], t: [246.96, 163.74] }, graded: { nt: [122.18, 90.89], t: [256.5, 171.02] } },
  { age: 71, preferred: { nt: [94.22, 76.5], t: [120.82, 92.5] }, standard: { nt: [107.8, 86.31], t: [205.41, 142.35] }, substandard: { nt: [124.23, 92.39], t: [258.72, 173.66] }, graded: { nt: [129.51, 95.27], t: [268.91, 181.26] } },
  { age: 72, preferred: { nt: [99.56, 80.84], t: [126.72, 98.4] }, standard: { nt: [116.65, 90.93], t: [217.82, 149.4] }, substandard: { nt: [131.28, 97.59], t: [270.61, 182.16] }, graded: { nt: [135.93, 102.32], t: [281.08, 190.23] } },
  { age: 73, preferred: { nt: [105.92, 85.18], t: [132.59, 104.28] }, standard: { nt: [125.66, 99.23], t: [237.28, 163.75] }, substandard: { nt: [143.68, 106.93], t: [299.83, 199.69] }, graded: { nt: [150.12, 112.67], t: [311.43, 206.86] } },
  { age: 74, preferred: { nt: [112.45, 91.28], t: [138.5, 110.17] }, standard: { nt: [132.09, 105.73], t: [258.47, 176.02] }, substandard: { nt: [155.05, 116.6], t: [322.09, 214.63] }, graded: { nt: [161.85, 125.93], t: [336.2, 223.41] } },
  { age: 75, preferred: { nt: [118.68, 97.55], t: [144.38, 116.07] }, standard: { nt: [141.21, 114.56], t: [276.39, 191.48] }, substandard: { nt: [166.41, 126.56], t: [347.13, 230.9] }, graded: { nt: [173.71, 137.66], t: [361.19, 239.88] } },
  { age: 76, preferred: { nt: [125.82, 103.39], t: [153.02, 123.04] }, standard: { nt: [152.4, 123.3], t: [297.57, 207.06] }, substandard: { nt: [182.4, 137.28], t: [369.84, 246.99] }, graded: { nt: [190.61, 152.88], t: [383.2, 257.69] } },
  { age: 77, preferred: { nt: [134.23, 109.24], t: [161.7, 129.99] }, standard: { nt: [163.62, 133.09], t: [320.72, 225.66] }, substandard: { nt: [194.18, 147.5], t: [390.45, 263.48] }, graded: { nt: [202.71, 164.26], t: [407.27, 273.05] } },
  { age: 78, preferred: { nt: [142.89, 116.11], t: [170.36, 136.96] }, standard: { nt: [181.65, 145.6], t: [347.91, 251.35] }, substandard: { nt: [211.4, 161.3], t: [429.69, 292.8] }, graded: { nt: [220.68, 183.39], t: [451.77, 305.3] } },
  { age: 79, preferred: { nt: [151.61, 120.8], t: [179.02, 143.93] }, standard: { nt: [196.95, 157.04], t: [379.73, 279.42] }, substandard: { nt: [233.42, 177.37], t: [475.21, 318.71] }, graded: { nt: [243.91, 201.66], t: [496.54, 330.77] } },
  { age: 80, preferred: { nt: [158.98, 125.22], t: [187.68, 153.81] }, standard: { nt: [212.65, 173.37], t: [407.83, 311.36] }, substandard: { nt: [253.63, 191.77], t: [511.91, 351.65] }, graded: { nt: [265.05, 218.04], t: [533.64, 366.07] } },
];

/**
 * Medication -> rating-class restriction, from the Generational Life
 * Underwriting Guide.
 *
 *   'allow'         - "All rating classes"
 *   'not_preferred' - "Std, Sub-Std, Graded Benefit" (Preferred is ruled out)
 *   'graded'        - "Graded Benefit" only
 *   'refer'         - "Review medical conditions"
 *
 * Tuple: [medication, conditions the guide associates with it, action]
 */
export type MedicationAction = 'allow' | 'not_preferred' | 'graded' | 'refer';
export const GENERATIONAL_LIFE_MEDICATIONS: Array<[string, string, MedicationAction]> = [
  ['abacavir', 'HIV', 'graded'],
  ['abarelix', 'Cancer', 'graded'],
  ['abciximab', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve', 'graded'],
  ['abilify', 'Depression, Schizophrenia', 'not_preferred'],
  ['acarbose', 'Diabetes Mellitus', 'not_preferred'],
  ['accupril', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['accuretic', 'High Blood Pressure, Angina, Congestive Heart Failure', 'not_preferred'],
  ['acebutolol', 'High Blood Pressure', 'not_preferred'],
  ['aceon', 'High Blood Pressure', 'not_preferred'],
  ['aceta', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['acetaminophen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['acetazolamide', 'Glaucoma, Epilepsy', 'allow'],
  ['acetocot', 'Arthritis, Asthma', 'allow'],
  ['acetohexamide', 'Diabetes Mellitus', 'not_preferred'],
  ['aciphex', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['acridine', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['actigall', 'Gallstones', 'allow'],
  ['actiq', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['activase', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['actonel', 'Osteoporosis', 'allow'],
  ['actos', 'Diabetes Mellitus', 'not_preferred'],
  ['actron', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['acular', 'Cataracts', 'allow'],
  ['acyclovir', 'Sexually transmitted Disease', 'allow'],
  ['adalat', 'High Blood Pressure, Migraine Headache, Congestive Heart Failure', 'not_preferred'],
  ['adalat cc', 'High Blood Pressure, Angina', 'not_preferred'],
  ['adalimumab', 'Rheumatoid Arthritis', 'not_preferred'],
  ['adapin', 'Depression', 'allow'],
  ['adderall xr', 'Attention Deficit Hyperactivity Disorder', 'allow'],
  ['adrucil', 'Cancer', 'graded'],
  ['adsorbocarpine', 'Glaucoma', 'allow'],
  ['advair', 'Asthma', 'allow'],
  ['advicor', 'High Cholesterol', 'allow'],
  ['aerobid', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['aerolate', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['aggrastat', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['aggrenox', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['agrylin', 'Thrombocytopenia', 'graded'],
  ['airet', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['akineton', 'Parkinson\'s Disease', 'graded'],
  ['albuterol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['aldactazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['aldactone', 'High Blood Pressure, Angina', 'not_preferred'],
  ['aldoclor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['aldomet', 'High Blood Pressure, Angina', 'not_preferred'],
  ['aldoril', 'High Blood Pressure, Angina', 'not_preferred'],
  ['alefacept', 'Psoriasis', 'allow'],
  ['alendronate', 'Osteoporosis', 'allow'],
  ['alfuzosin', 'Benign Prostatic Hyperplasia (BPH)', 'allow'],
  ['allopurinol', 'Gout', 'allow'],
  ['almotriptan', 'Migraine Headache', 'allow'],
  ['alosetron', 'Irritable Bowel Syndrome', 'allow'],
  ['alphagan', 'Glaucoma', 'allow'],
  ['alprazolam', 'Anxiety', 'allow'],
  ['alprenolol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['altace', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['altoprev', 'High Cholesterol', 'allow'],
  ['altretamine', 'Cancer', 'graded'],
  ['alupent', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['amantadine', 'Parkinson\'s Disease', 'graded'],
  ['amaryl', 'Diabetes Mellitus', 'not_preferred'],
  ['ambien', 'Depression, Anxiety', 'allow'],
  ['amerge', 'Migraine Headache', 'allow'],
  ['amidrine', 'Headaches', 'refer'],
  ['amigesic', 'Rheumatoid Arthritis, Back pain, Joint Pain', 'not_preferred'],
  ['amiloride', 'High Blood Pressure, Angina', 'not_preferred'],
  ['aminoguanidine', 'Diabetes Mellitus', 'not_preferred'],
  ['aminophylline', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['amiodarone', 'Arrhythmia', 'allow'],
  ['amitriptyline', 'Depression', 'allow'],
  ['amlodipine', 'High Blood Pressure, Angina, Congestive Heart Failure', 'allow'],
  ['amoxapine', 'Depression', 'allow'],
  ['amplex', 'Chronic Organic Brain Disorder,Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['anafranil', 'Anxiety', 'allow'],
  ['anagrelide', 'Thrombocytopenia', 'graded'],
  ['anakinra', 'Rheumatoid Arthritis', 'graded'],
  ['ancrod', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['anexsia', 'Back, Hip, Joint Disorders, Arthritis', 'refer'],
  ['antispas', 'Irritable Bowel Syndrome', 'allow'],
  ['antivert', 'Vertigo', 'allow'],
  ['anturane', 'Gout', 'allow'],
  ['apokyn', 'Parkinson\'s Disease', 'graded'],
  ['apomorphine', 'Parkinson\'s Disease', 'graded'],
  ['apresazide', 'High Blood Pressure, Angina', 'allow'],
  ['apresoline', 'High Blood Pressure, Angina', 'allow'],
  ['aquatensen', 'High Blood Pressure, Angina', 'allow'],
  ['aralen', 'Arthritis', 'allow'],
  ['arava', 'Rheumatoid Arthritis', 'allow'],
  ['ardeparin', 'Deep Vein Thrombosis', 'graded'],
  ['aredia', 'Paget\'s Disease, Cancer', 'allow'],
  ['arfonad', 'High Blood Pressure, Angina', 'allow'],
  ['aricept', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['arimidex', 'Breast Cancer, Cancer', 'graded'],
  ['aripiprazole', 'Schizophrenia', 'graded'],
  ['arixtra', 'Deep Vein Thrombosis', 'graded'],
  ['arlidin', 'High Blood Pressure, Angina', 'allow'],
  ['armour', 'Thyroid Thyroid Disorder', 'allow'],
  ['aromasin', 'Cancer', 'graded'],
  ['artane', 'Parkinson\'s Disease', 'graded'],
  ['arthrotec', 'Osteoarthritis, Rheumatoid Arthritis', 'allow'],
  ['asendin', 'Depression', 'allow'],
  ['asmalix', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['asparaginase', 'Leukemia', 'graded'],
  ['asthmahaler', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['asthmanefrin', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['atacand', 'High Blood Pressure', 'allow'],
  ['atamet', 'Parkinson\'s Disease', 'graded'],
  ['atarax', 'Anxiety', 'allow'],
  ['atenolol', 'High Blood Pressure, Angina', 'allow'],
  ['ativan', 'Anxiety', 'allow'],
  ['atorvastatin', 'High Cholesterol', 'allow'],
  ['atretol', 'Epilepsy, Seizure', 'allow'],
  ['atromid', 'High Cholesterol', 'allow'],
  ['atrovent', 'Emphysema, COPD', 'graded'],
  ['auranofin', 'Rheumatoid Arthritis', 'graded'],
  ['aurothioglucose', 'Rheumatoid Arthritis', 'graded'],
  ['aurothiomalate', 'Rheumatoid Arthritis', 'graded'],
  ['avandamet', 'Diabetes Mellitus', 'allow'],
  ['avandia', 'Diabetes Mellitus', 'allow'],
  ['avapro', 'High Blood Pressure, Angina', 'allow'],
  ['avastin', 'Cancer', 'graded'],
  ['aventyl', 'Depression', 'allow'],
  ['avinza', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['avodart', 'Prostate Enlargement', 'allow'],
  ['avonex', 'Multiple Sclerosis', 'graded'],
  ['axert', 'Migraine Headache', 'allow'],
  ['axid', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['azathioprine', 'Chronic Active Hepatitis, Regional Enteritis, Ulcerative Colitis', 'allow'],
  ['azmacort', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['azt', 'HIV', 'graded'],
  ['azulfidine', 'Regional Enteritis, Ulcerative Colitis', 'allow'],
  ['baclofen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['barbiturates', 'Anxiety', 'allow'],
  ['baycol', 'High Cholesterol', 'allow'],
  ['becaplermin', 'Diabetic Ulcers', 'allow'],
  ['beclomethasone', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['beclovent', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['beconase', 'Asthma', 'allow'],
  ['benazepril', 'High Blood Pressure, Angina, Congestive Heart Failure', 'allow'],
  ['bendroflumethiazide', 'High Blood Pressure, Angina', 'allow'],
  ['benemid', 'Gout', 'allow'],
  ['benicar', 'High Blood Pressure', 'allow'],
  ['bentyl', 'Colitis, Peptic Ulcer', 'allow'],
  ['benzodiazepine', 'Anxiety', 'allow'],
  ['benzonatate', 'Bronchitis, Lung Infections', 'allow'],
  ['benzthiazide', 'High Blood Pressure, Angina', 'allow'],
  ['benztropine', 'Parkinson\'s Tremor', 'allow'],
  ['bepridil', 'Angina', 'graded'],
  ['betamethasone', 'Oral / Injectable Steroid', 'allow'],
  ['betapace', 'Arrhythmia', 'graded'],
  ['betaseron', 'Multiple Sclerosis', 'graded'],
  ['betimol', 'Glaucoma', 'allow'],
  ['bevacizumab', 'Cancer', 'graded'],
  ['bextra', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['bicalutamide', 'Cancer', 'graded'],
  ['bisoprolol', 'High Blood Pressure', 'allow'],
  ['bitolterol', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['blocadren', 'High Blood Pressure, Arrhythmia, Angina', 'allow'],
  ['bonine', 'Vertigo', 'allow'],
  ['brethaire', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['brethine', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['bretylium', 'Arrhythmia', 'graded'],
  ['bretylol', 'Arrhythmia', 'graded'],
  ['bricanyl', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['bromocriptine', 'Parkinson\'s Disease', 'graded'],
  ['bronkometer', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['bronkosol', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['buclizine', 'Vertigo', 'allow'],
  ['bufferin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['bumetanide', 'High Blood Pressure, Angina', 'allow'],
  ['bumex', 'High Blood Pressure, Angina', 'allow'],
  ['bupropion', 'Depression, Smoking Cessation', 'allow'],
  ['buspar', 'Anxiety', 'allow'],
  ['buspirone', 'Anxiety', 'allow'],
  ['butalbital', 'Headaches', 'allow'],
  ['byetta', 'Diabetes Mellitus', 'graded'],
  ['cafergot', 'Headaches', 'allow'],
  ['calan', 'High Blood Pressure, Arrhythmia, Angina', 'allow'],
  ['calcimar', 'Osteoporosis', 'allow'],
  ['calcitonin-salmon', 'Osteoporosis', 'allow'],
  ['cama', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['campral', 'Alcohol Abuse', 'graded'],
  ['canasa', 'Chron\'s Disease', 'allow'],
  ['candesartan', 'High Blood Pressure', 'allow'],
  ['capecitabine', 'Cancer', 'graded'],
  ['capoten', 'High Blood Pressure, Arrhythmia, Angina', 'allow'],
  ['capozide', 'High Blood Pressure, Angina', 'allow'],
  ['captopril', 'High Blood Pressure, Angina', 'allow'],
  ['captopril-', 'Hydrochlorothiazide High Blood Pressure, Angina, Congestive Heart Failure', 'allow'],
  ['carafate', 'Gastritis, Gastroesophageal Reflux, Peptic Ulcer', 'allow'],
  ['carbamate', 'Anxiety', 'allow'],
  ['carbamazepine', 'Epilepsy, Seizure', 'allow'],
  ['carbatrol', 'Seizure, Epilepsy', 'allow'],
  ['carbex', 'Parkinson\'s Disease', 'graded'],
  ['carbidopa', 'Parkinson\'s Disease', 'graded'],
  ['carbidopa-levodopa', 'Restless Leg Syndrome, Disease', 'allow'],
  ['cardene', 'High Blood Pressure, Angina', 'allow'],
  ['cardilate', 'High Blood Pressure, Angina', 'allow'],
  ['cardioquin', 'High Blood Pressure, Arrhythmia, Angina', 'allow'],
  ['cardizem', 'High Blood Pressure, Angina', 'allow'],
  ['cardura', 'High Blood Pressure, Angina', 'allow'],
  ['carisoprodol', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['carteolol', 'High Blood Pressure', 'allow'],
  ['cartia xt', 'High Blood Pressure, Angina', 'allow'],
  ['cartrol', 'High Blood Pressure', 'allow'],
  ['carvedilol', 'High Blood Pressure, Angina', 'allow'],
  ['cataflam', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['catapres', 'High Blood Pressure, Angina', 'allow'],
  ['cedilanid-d', 'Congestive Heart Failure', 'graded'],
  ['cefzil', 'Bronchitis', 'allow'],
  ['celebrex', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['celecoxib', 'Arthritis', 'allow'],
  ['celestone', 'Oral / Injectable Steroid', 'graded'],
  ['celexa', 'Depression', 'allow'],
  ['cellcept', 'Immunosuppressant, Anti-Rejection due to organ transplant', 'graded'],
  ['celontin', 'Epilepsy, Seizure', 'allow'],
  ['centrax', 'Anxiety', 'allow'],
  ['cerebyx', 'Seizure, Epilepsy', 'allow'],
  ['ceredase', 'Gaucher\'s Disease', 'graded'],
  ['cerespan', 'High Blood Pressure, Angina', 'allow'],
  ['cerezyme', 'Gaucher\'s Disease', 'graded'],
  ['cerivastatin', 'High Cholesterol', 'allow'],
  ['cevimeline', 'Sjogren\'s Syndrome', 'allow'],
  ['chenodeoxycholic', 'Acid Gallstones', 'allow'],
  ['chenodiol', 'Gallstones', 'allow'],
  ['chlordiazepoxide', 'Anxiety', 'allow'],
  ['chloroquine', 'Arthritis', 'allow'],
  ['chlorothiazide', 'High Blood Pressure, Angina', 'allow'],
  ['chlorphenesin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['chlorpromazine', 'Psychotic Disorders', 'graded'],
  ['chlorpropamide', 'Diabetes Mellitus', 'allow'],
  ['chlorprothixene', 'Psychosis', 'graded'],
  ['chlorthalidone', 'High Blood Pressure, Angina', 'allow'],
  ['chlorzoxazone', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['choledyl', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['cholestyramine', 'High Cholesterol', 'allow'],
  ['choloxin', 'High Cholesterol', 'allow'],
  ['cilostazol', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve', 'graded'],
  ['cimetidine', 'Gastritis, Gastroesophageal Reflux, Peptic Ulcer', 'allow'],
  ['cinacalcet', 'Hyperparathyroidism', 'graded'],
  ['cinalone', 'Oral Steroid', 'allow'],
  ['cipro', 'Urinary Tract Infection', 'allow'],
  ['ciprofloxacin', 'Urinary Tract Infection', 'allow'],
  ['cisapride', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['citalopram', 'Depression', 'allow'],
  ['cladribine', 'Cancer', 'graded'],
  ['clindex', 'Ulcers, Irritable Bowel Syndrome', 'allow'],
  ['clofibrate', 'Cholesterol', 'allow'],
  ['clomipramine', 'Anxiety, Obsessive-Compulsive Disorder', 'allow'],
  ['clonazepam', 'Epilepsy, Seizure', 'allow'],
  ['clonidine', 'High Blood Pressure, Angina', 'allow'],
  ['clonopin', 'Epilepsy, Seizure', 'allow'],
  ['clopidogrel', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve', 'graded'],
  ['clorazepate', 'Anxiety', 'allow'],
  ['clozapine', 'Psychotic Disorders', 'graded'],
  ['clozaril', 'Psychotic Disorders', 'graded'],
  ['codeine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['cogentin', 'Psychotic Disorders', 'graded'],
  ['cognex', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['colbenemid', 'Gout', 'allow'],
  ['colchicine', 'Scleroderma, Gout', 'allow'],
  ['colestid', 'High Cholesterol', 'allow'],
  ['colestipol', 'High Cholesterol', 'allow'],
  ['collagen-alginate', 'Topical Diabetic Ulcers', 'graded'],
  ['col-probenecid', 'Gout', 'allow'],
  ['combid', 'Colitis, Peptic Ulcer', 'allow'],
  ['combipres', 'High Blood Pressure, Angina', 'allow'],
  ['combivent', 'Asthma, Bronchitis, Emphysema, COPD', 'graded'],
  ['combivir', 'HIV Sub Standard', 'graded'],
  ['compazine', 'Psychosis', 'graded'],
  ['comvax', 'Parkinson\'s Disease', 'graded'],
  ['concerta', 'Attention Deficit Hyperactivity Disorder', 'allow'],
  ['copaxone', 'Multiple Sclerosis Sub Standard', 'graded'],
  ['cordarone', 'Arrhythmia', 'graded'],
  ['coreg', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['corgard', 'High Blood Pressure, Angina', 'not_preferred'],
  ['cortisone', 'Oral / Injectable Steroid', 'allow'],
  ['cortone', 'Acetate Oral / Injectable Steroid', 'allow'],
  ['corzide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['cosopt', 'Glaucoma', 'allow'],
  ['cotazym', 'Pancreatic Insufficiency', 'graded'],
  ['coumadin', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['covera', 'High Blood Pressure, Angina', 'not_preferred'],
  ['covera-hs', 'High Blood Pressure, Angina', 'not_preferred'],
  ['cozaar', 'High Blood Pressure, Angina', 'not_preferred'],
  ['crestor', 'High Cholesterol', 'allow'],
  ['cromolyn', 'Sodium Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['crystodigin', 'Arrhythmia, Congestive Heart Failure, Heart Condition', 'graded'],
  ['cuprimine', 'Rheumatoid Arthritis, Kidney Stones, Wilson\'s Disease', 'graded'],
  ['cyclandelate', 'TIA, Memory Loss, Dementia', 'graded'],
  ['cyclobenzaprine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['cyclophosphamide', 'Chronic Active Hepatitis, Regional Enteritis, Ulcerative Colitis, Cancer, Kidney Failure', 'graded'],
  ['cyclospasmol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['cyclosporine', 'Lupus, Scleroderma, Cancer, Organ Transplant', 'graded'],
  ['cyclothiazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['cylert', 'Attention Deficit Hyperactivity Disorder', 'allow'],
  ['cytotec', 'Peptic Ulcer Disease', 'allow'],
  ['cytoxan', 'Chronic Active Hepatitis, Regional Enteritis, Ulcerative Colitis, Cancer, Kidney Failure, Lupus, Scleroderma', 'graded'],
  ['dalalone', 'Injectable Steroid', 'graded'],
  ['dalteparin', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['danaparoid', 'Deep Vein Thrombosis', 'graded'],
  ['dantrolene', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['daypro', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['decadron', 'Oral / Injectable Steroid', 'not_preferred'],
  ['deferoxamine', 'Hemochromatosis', 'graded'],
  ['deltasone', 'Oral Steroid', 'not_preferred'],
  ['demadex', 'High Blood Pressure, Angina', 'not_preferred'],
  ['demerol', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['demi-regroton', 'High Blood Pressure, Angina', 'not_preferred'],
  ['depacon', 'Seizure, Epilepsy', 'not_preferred'],
  ['depakene', 'Epilepsy, Seizure', 'not_preferred'],
  ['depakote', 'Epilepsy, Seizure', 'not_preferred'],
  ['depen', 'Rheumatoid Arthritis, Kidney Stones, Wilson\'s Disease', 'graded'],
  ['depo-medrol', 'Injectable Steroid', 'graded'],
  ['deponit', 'NT Angina', 'not_preferred'],
  ['depo-provera', 'Endometriosis, Menstruation', 'allow'],
  ['deprynel', 'Parkinson\'s Disease', 'graded'],
  ['deserpidine', 'High Blood Pressure', 'allow'],
  ['desferal', 'Hemochromatosis', 'graded'],
  ['desipramine', 'Depression', 'allow'],
  ['destinex', 'Parkinson\'s Disease', 'graded'],
  ['desyrel', 'Depression', 'allow'],
  ['detrol', 'Urinary Incontinence', 'allow'],
  ['dexamethasone', 'Oral / Injectable Steroid', 'graded'],
  ['dexasone', 'Oral / Injectable Steroid', 'graded'],
  ['dextrostat', 'Attention Deficit Hyperactivity Disorder', 'allow'],
  ['dextrothyroxine', 'High Cholesterol', 'allow'],
  ['diabeta', 'Diabetes Mellitus', 'allow'],
  ['diabinese', 'Diabetes Mellitus', 'allow'],
  ['dia-gesic', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['dialume', 'Peptic Ulcer Disease', 'allow'],
  ['diamox', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diazepam', 'Anxiety', 'allow'],
  ['dibenzyline', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diclofenac', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['dicyclomine', 'Colitis, Peptic Ulcer', 'allow'],
  ['didronel', 'Paget\'s Disease, Bone Density', 'allow'],
  ['diflunisal', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['digitek', 'Arrhythmia', 'not_preferred'],
  ['digoxin', 'Arrhythmia, Congestive Heart Failure, Heart Condition', 'graded'],
  ['dihydroergotamine', 'Headaches', 'allow'],
  ['dilacor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['dilantin', 'Epilepsy, Seizure', 'allow'],
  ['dilatrate-sr', 'High Blood Pressure, Angina', 'not_preferred'],
  ['dilaudid', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['dilor', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['diltiazem', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diovan', 'High Blood Pressure, Angina', 'not_preferred'],
  ['dipentum', 'Ulcerative Colitis', 'allow'],
  ['diphenoxylate', 'Regional Enteritis, Ulcerative Colitis', 'allow'],
  ['diphenylhydantoin', 'Epilepsy, Seizure', 'not_preferred'],
  ['dipyridamole', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['disalcid', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['disopyramide', 'Arrhythmia', 'allow'],
  ['diucardin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diulo', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diupress', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diuril', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diutensen', 'High Blood Pressure, Angina', 'not_preferred'],
  ['diutensen-r', 'High Blood Pressure, Angina', 'not_preferred'],
  ['divalproex', 'Seizure, Epilepsy', 'not_preferred'],
  ['dolobid', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['donepezil', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['donnatal', 'Colitis, Peptic Ulcer', 'allow'],
  ['doriden', 'Anxiety', 'allow'],
  ['dovonex', 'Psoriasis', 'allow'],
  ['doxazosin', 'High Blood Pressure, Urinary Obstruction Symptoms of BPH', 'allow'],
  ['doxepin', 'Depression', 'allow'],
  ['d-penicillamine', 'Scleroderma, Lupus', 'graded'],
  ['duracet', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['duragesic', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['duraquin', 'Arrhythmia', 'allow'],
  ['dyazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['dynacirc', 'High Blood Pressure, Angina', 'not_preferred'],
  ['dyphylline', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['dyrenium', 'High Blood Pressure, Angina', 'not_preferred'],
  ['easprin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['ec-naprosyn', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['ecotrin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['edecin', 'High Blood Pressure, Angina, Congestive Heart Failure', 'not_preferred'],
  ['edecrin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['effexor', 'Depression', 'allow'],
  ['elavil', 'Depression', 'allow'],
  ['eldepryl', 'Psychotic Disorders', 'graded'],
  ['elixicon', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['elixophyllin', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['emcyt', 'Prostate Cancer, Cancer', 'graded'],
  ['empirin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['enalapril', 'High Blood Pressure, Angina, Congestive Heart Failure', 'not_preferred'],
  ['enalapril-felodipine', 'High Blood Pressure', 'allow'],
  ['enbrel', 'Rheumatoid Arthritis', 'graded'],
  ['endep', 'Depression', 'allow'],
  ['enduron', 'High Blood Pressure, Angina', 'not_preferred'],
  ['enduronyl', 'High Blood Pressure, Angina', 'not_preferred'],
  ['enoxaparin', 'Prevention Of Deep Vein Thrombosis', 'graded'],
  ['entacapone', 'Parkinson\'s Disease', 'graded'],
  ['ephed', 'II Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['epogen', 'Severe Anemia', 'graded'],
  ['eptifibatide', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['equanil', 'Anxiety', 'allow'],
  ['ergoloid', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['ergomar', 'Migraine Headache', 'allow'],
  ['ergostat', 'Headaches', 'allow'],
  ['ergotamine', 'Tartrate Headaches', 'allow'],
  ['erythrityl', 'Angina', 'graded'],
  ['erythropoietin', 'Severe Anemia', 'graded'],
  ['esidrix', 'High Blood Pressure, Angina', 'not_preferred'],
  ['esimil', 'High Blood Pressure, Angina', 'not_preferred'],
  ['eskalith', 'Bipolar Disorder', 'graded'],
  ['etanercept', 'Rheumatoid Arthritis, Back pain, Joint Pain', 'graded'],
  ['ethatab', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ethchlorvynol', 'Anxiety', 'allow'],
  ['ethmozine', 'Arrhythmia', 'graded'],
  ['ethopropazine', 'Parkinson\'s Disease', 'graded'],
  ['ethosuximide', 'Epilepsy, Seizure', 'not_preferred'],
  ['ethotoin', 'Seizure, Epilepsy', 'not_preferred'],
  ['etidronate', 'Osteoporosis', 'allow'],
  ['etodolac', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['etrafon', 'Depression', 'allow'],
  ['eutonyl', 'High Blood Pressure, Angina', 'not_preferred'],
  ['evista', 'Osteoporosis', 'allow'],
  ['excedrin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['exelon', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['exna', 'High Blood Pressure, Angina', 'not_preferred'],
  ['famciclovir', 'Sexually Transmitted Disease', 'allow'],
  ['famotidine', 'Gastroesophageal Reflux, Peptic Ulcer', 'allow'],
  ['famvir', 'Sexually Transmitted Disease', 'allow'],
  ['fareston', 'Breast Cancer, Cancer', 'graded'],
  ['faslodex', 'Cancer', 'graded'],
  ['felbamate', 'Epilepsy, Seizure', 'not_preferred'],
  ['felbatol', 'Epilepsy, Seizure', 'not_preferred'],
  ['feldene', 'Back, Hip, Joint Disorders', 'allow'],
  ['felodipine', 'High Blood Pressure', 'allow'],
  ['femara', 'Breast Cancer, Cancer', 'graded'],
  ['fenoprofen', 'Back,Joint Disorders, Arthritis', 'allow'],
  ['fibracol', 'Diabetic Ulcers', 'graded'],
  ['finasteride', 'Benign Prostatic Hyperplasia (BPH)', 'allow'],
  ['fioricet', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['fiorinal', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['flagyl', 'Regional Enteritis', 'allow'],
  ['flecainide', 'Arrhythmia', 'graded'],
  ['flexeril', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['flolan', 'High Blood Pressure, Angina', 'not_preferred'],
  ['flomax', 'Benign Prostatic Hyperplasia (BPH)', 'allow'],
  ['flonase', 'Asthma', 'allow'],
  ['florinef', 'Addison\'s Disease', 'graded'],
  ['flosequinan', 'Congestive Heart Failure', 'graded'],
  ['flovent', 'Asthma, Bronchitis, COPD', 'not_preferred'],
  ['fludrocortisone', 'Addison\'s Disease, Diabetes', 'graded'],
  ['flunisolide', 'Asthma, Emphysema, COPD', 'not_preferred'],
  ['fluoxetine', 'Depression, Bulimia Nervosa', 'not_preferred'],
  ['fluphenazine', 'Psychotic Disorders', 'graded'],
  ['fluticasone', 'Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['fluvastatin', 'High Cholesterol', 'allow'],
  ['fluvoxamine', 'Anxiety, OCD', 'allow'],
  ['folex', '(Methotrexate) Immunosuppressant, Rheumatoid Arthritis, Psoriasis', 'graded'],
  ['fosamax', 'Osteoporosis', 'allow'],
  ['fosinopril', 'High Blood Pressure, Angina, Congestive Heart Failure', 'not_preferred'],
  ['fosphenytoin', 'Seizure, Epilepsy', 'not_preferred'],
  ['fragmin', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['frova', 'Migraine Headache', 'allow'],
  ['furosemide', '(80mg or more/day) All Conditions', 'graded'],
  ['gabapentin', 'Epilepsy, Seizure', 'not_preferred'],
  ['gabitril', 'Epilepsy', 'not_preferred'],
  ['gemfibrozil', 'High Cholesterol', 'allow'],
  ['glatiramer', 'Multiple Sclerosis', 'graded'],
  ['glaucon', 'Glaucoma', 'not_preferred'],
  ['glibenclamide', 'Diabetes Mellitus', 'not_preferred'],
  ['glimepiride', 'Diabetes Mellitus', 'not_preferred'],
  ['glipizide', 'Diabetes Mellitus', 'not_preferred'],
  ['glucophage', 'Diabetes Mellitus', 'not_preferred'],
  ['glucotrol', 'Diabetes Mellitus', 'not_preferred'],
  ['glucovance', 'Diabetes Mellitus', 'not_preferred'],
  ['glutethimide', 'Anxiety', 'allow'],
  ['glyburide', 'Diabetes Mellitus', 'not_preferred'],
  ['glyburide-metformin', 'Diabetes Mellitus', 'not_preferred'],
  ['glynase', 'Diabetes Mellitus', 'not_preferred'],
  ['glyset', 'Diabetes Mellitus', 'not_preferred'],
  ['gold', 'Arthritis', 'graded'],
  ['guanabenz', 'High Blood Pressure, Angina', 'not_preferred'],
  ['guanadrel', 'High Blood Pressure, Angina', 'not_preferred'],
  ['guanethidine', 'High Blood Pressure, Angina', 'not_preferred'],
  ['halazepam', 'Anxiety', 'allow'],
  ['halcion', 'Depression, Anxiety', 'allow'],
  ['haldol', 'Psychotic Disorders', 'graded'],
  ['halfprin', 'Rheumatoid Arthritis, Back pain, Joint Pain', 'not_preferred'],
  ['haloperidol', 'Psychotic Disorders', 'graded'],
  ['harmonyl', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hctz', 'High Blood Pressure', 'allow'],
  ['helidac', 'Ulcers', 'allow'],
  ['heparin', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['hexadrol', 'Oral / Injectable Steroid', 'graded'],
  ['humalog', 'Insulin Dependent Diabetes Mellitus', 'graded'],
  ['humira', 'Rheumatoid Arthritis', 'graded'],
  ['humulin', 'Insulin Dependent Diabetes Mellitus', 'graded'],
  ['hydeltra', 'Injectable Steroid', 'graded'],
  ['hydeltrasol', 'Injectable Steroid', 'graded'],
  ['hydergine', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['hydralazine', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hydra-zide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hydrea', 'Cancer, Sickle Cell Anemia', 'graded'],
  ['hydrochlorothiazide', '(HCTZ) High Blood Pressure, Edema, Angina, Congestive Heart Failure', 'not_preferred'],
  ['hydrocodone', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['hydrocodone/acetaminophen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['hydrocortisone', 'Oral / Injectable Steroid', 'not_preferred'],
  ['hydrocortone', 'Injectable Steroid', 'graded'],
  ['hydrodiuril', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hydroflumethiazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hydromox', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hydropres', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hydroxychloroquine', 'Rheumatoid Arthritis, Liver Disease, Lupus, Scleroderma', 'not_preferred'],
  ['hygroton', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hylorel', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hyoscyamine', 'Peptic Ulcer Disease, Irritable Bowel, Pancreatitis', 'allow'],
  ['hyperstat', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hytrin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['hyzaar', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ibu', 'Tablets Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['ibuprofen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['iletin', 'II NPH Pork Insulin Dependent Diabetes Mellitus', 'graded'],
  ['ilopan', 'Choline Insulin Dependent Diabetes Mellitus', 'graded'],
  ['imdur', 'High Blood Pressure, Angina', 'not_preferred'],
  ['imferon', 'Anemia', 'graded'],
  ['imiglucerase', 'Injection Gaucher\'s Disease', 'graded'],
  ['imipramine', 'Depression', 'allow'],
  ['imitrex', 'Headaches', 'allow'],
  ['imuran', 'Chronic Active Hepatitis, Regional Enteritis, Ulcerative Colitis', 'graded'],
  ['indapamide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['inderal', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['inderal la', 'High Blood Pressure, Angina', 'not_preferred'],
  ['inderide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['indomethacin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['inh', 'Tuberculosis (TB)', 'graded'],
  ['inocor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['insulin', 'Insulin Dependent Diabetes Mellitus', 'graded'],
  ['intal', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['integrilin', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['interferon', 'Cancer, Hepatitis, AIDS', 'graded'],
  ['inversine', 'High Blood Pressure', 'allow'],
  ['ipratropium', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['irbesartan', 'High Blood Pressure', 'allow'],
  ['iron', 'Dextran Anemia', 'allow'],
  ['ismelin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ismo', 'High Blood Pressure, Angina', 'not_preferred'],
  ['iso-bid', 'High Blood Pressure, Angina', 'not_preferred'],
  ['isocarboxazid', 'Depression', 'allow'],
  ['isochron', 'High Blood Pressure, Angina', 'not_preferred'],
  ['isoetharine', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['isoniazid', 'Tuberculosis (TB)', 'graded'],
  ['isoproterenol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['isoptin', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['isordil', 'Angina, Congestive Heart Failure', 'graded'],
  ['isosorbide', 'Dinitrate Angina, Congestive Heart Failure', 'graded'],
  ['isuprel', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['i-thyroxine', 'Thyroid Disorder', 'allow'],
  ['kemadrin', 'Parkinson\'s Disease', 'graded'],
  ['kenalog', 'Injectable Steroid', 'graded'],
  ['kerlone', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ketoprofen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['kineret', 'Rheumatoid Arthritis', 'graded'],
  ['klonopin', 'Epilepsy, Seizure', 'allow'],
  ['labetalol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['labid', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['lamictal', 'Epilepsy, Seizure', 'not_preferred'],
  ['lamotrigine', 'Epilepsy, Seizure', 'not_preferred'],
  ['lanoxicaps', 'Arrhythmia, Congestive Heart Failure, Heart Condition', 'graded'],
  ['lanoxin', 'Arrhythmia, Congestive Heart Failure, Heart Condition', 'graded'],
  ['lantus', 'Insulin Dependent Diabetes Mellitus', 'graded'],
  ['larodopa', 'Parkinson\'s Disease, Tremor', 'not_preferred'],
  ['lasix', '(80mg or more/day) Arrhythmia, Congestive Heart Failure, Heart Condition', 'graded'],
  ['l-dopa', 'Parkinson\'s Disease', 'graded'],
  ['lente', 'Insulin Insulin Dependent Diabetes Mellitus', 'graded'],
  ['lescol', 'High Cholesterol', 'allow'],
  ['letrozole', 'Breast Cancer, Cancer', 'graded'],
  ['leucovorin', 'Cancer', 'graded'],
  ['leukeran', 'Immunosuppressant, Cancer', 'graded'],
  ['levalbuterol', 'Asthma', 'allow'],
  ['levetiracetam', 'Seizure, Epilepsy', 'not_preferred'],
  ['levophed', 'Arrhythmia', 'allow'],
  ['levothroid', 'Thyroid Disorder', 'allow'],
  ['levothyroxine', 'Thyroid Disorder', 'allow'],
  ['levoxyl', 'Thyroid Disorder', 'allow'],
  ['levsin', 'Peptic Ulcer Disease, Irritable Bowel, Pancreatitis', 'not_preferred'],
  ['lexapro', 'Depression', 'allow'],
  ['lexxel', 'High Blood Pressure, Angina', 'not_preferred'],
  ['lialda', 'Ulcerative Colitis', 'allow'],
  ['librax', 'Colitis, Peptic Ulcer', 'allow'],
  ['librium', 'Anxiety', 'allow'],
  ['limbitrol', 'Depression', 'allow'],
  ['lioresal', 'Multiple Sclerosis', 'graded'],
  ['lipitor', 'High Cholesterol', 'allow'],
  ['lipo-nicin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['liquid', 'Pred Oral Steroid', 'graded'],
  ['lisinopril', 'High Blood Pressure, Angina, Congestive Heart Failure', 'allow'],
  ['lithane', 'Bipolar Disorder', 'graded'],
  ['lithium', 'Bipolar Disorder', 'graded'],
  ['lithobid', 'Bipolar Disorder', 'graded'],
  ['lithonate', 'Bipolar Disorder', 'graded'],
  ['lithotabs', 'Bipolar Disorder', 'graded'],
  ['lodine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['lodrane', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['loniten', 'High Blood Pressure, Angina', 'not_preferred'],
  ['lopid', 'High Cholesterol', 'allow'],
  ['lopressor', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['lopurin', 'Immunosuppressant, Cancer', 'graded'],
  ['lorazepam', 'Anxiety', 'allow'],
  ['lorelco', 'High Cholesterol', 'allow'],
  ['lortab', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['losartan', 'High Blood Pressure', 'allow'],
  ['lotensin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['lotrel', 'High Blood Pressure, Angina', 'not_preferred'],
  ['lovastatin', 'High Cholesterol', 'allow'],
  ['lovenox', 'Prevention of Deep Vein Thrombosis', 'graded'],
  ['loxapine', 'Psychotic Disorders', 'graded'],
  ['loxitane', 'Psychotic Disorders', 'graded'],
  ['lozol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ludiomil', 'Depression', 'allow'],
  ['lufyllin', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['lunesta', 'Depression, Anxiety', 'allow'],
  ['lupron', 'Prostate Cancer, Cancer', 'graded'],
  ['luvox', 'Anxiety, Obsessive-Compulsive Disorder', 'allow'],
  ['lyrica', 'Fibromyalgia, shingles', 'allow'],
  ['macrobid', 'Urinary Tract Infection', 'allow'],
  ['macrodantin', 'Urinary Tract Infection', 'allow'],
  ['magan', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['magnesium', 'Salicylate Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['manoplax', 'Congestive Heart Failure', 'graded'],
  ['mao', 'Inhibitor Depression', 'allow'],
  ['maprotiline', 'Depression', 'allow'],
  ['marax', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['marplan', 'Depression', 'allow'],
  ['mavik', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['maxair', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['maxalt', 'Migraine Headache', 'allow'],
  ['maxzide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['mebaral', 'Epilepsy, Seizure', 'not_preferred'],
  ['meclicot', 'Vertigo', 'allow'],
  ['meclizine', 'Vertigo', 'allow'],
  ['meclofenamate', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['meclomen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['medihaler', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['medipren', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['medivert', 'Vertigo', 'allow'],
  ['medrol', 'Oral Steroid', 'not_preferred'],
  ['mefenamic', 'Acid Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['mellaril', 'Psychotic Disorders', 'graded'],
  ['meperidine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['mephobarbital', 'Epilepsy, Seizure', 'not_preferred'],
  ['meprobamate', 'Anxiety', 'allow'],
  ['mesalamine', 'Ulcerative Colitis', 'allow'],
  ['mesantoin', 'Seizure, Epilepsy', 'not_preferred'],
  ['mesoridazine', 'Psychotic Disorders', 'graded'],
  ['mestinon', 'Myasthenia Gravis', 'graded'],
  ['metahydrin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['metaprel', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['metaproterenol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['metatensin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['metformin', 'Diabetes Mellitus', 'not_preferred'],
  ['methadone', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['methaqualone', 'Anxiety', 'allow'],
  ['methazolamide', 'Seizure, Epilepsy', 'not_preferred'],
  ['methenamine', 'Urinary Tract Infection', 'allow'],
  ['methimazole', 'Thyroid Disorder', 'allow'],
  ['methocarbamol', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['methotrexate', '(15mg or more/week) All Conditions', 'graded'],
  ['methsuximide', 'Seizure, Epilepsy', 'not_preferred'],
  ['methyclothiazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['methyldopa', 'High Blood Pressure, Angina', 'not_preferred'],
  ['methylphenidate', 'Depression', 'allow'],
  ['methylprednisolone', 'Oral / Injectable Steroid', 'not_preferred'],
  ['methysergide', 'Maleate Headaches', 'allow'],
  ['metoclopramide', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['metolazone', 'High Blood Pressure, Angina', 'not_preferred'],
  ['metoprolol', 'High Blood Pressure', 'allow'],
  ['metronidazole', 'Regional Enteritis', 'allow'],
  ['metroprolol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['metyrosine', 'High Blood Pressure', 'allow'],
  ['mevacor', 'High Cholesterol', 'allow'],
  ['mexiletine', 'Arrhythmia', 'allow'],
  ['mexitil', 'Arrhythmia', 'allow'],
  ['miacalcin', 'Osteoporosis', 'allow'],
  ['micardis', 'High Blood Pressure, Angina, Congestive Heart Failure', 'not_preferred'],
  ['micronase', 'Diabetes Mellitus', 'allow'],
  ['microzide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['midamor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['midrin', 'Headaches', 'allow'],
  ['miglitol', 'Diabetes Mellitus', 'not_preferred'],
  ['migratine', 'Migraine Headache', 'allow'],
  ['miltown', 'Anxiety', 'allow'],
  ['minipress', 'High Blood Pressure, Angina', 'not_preferred'],
  ['minitran', 'High Blood Pressure, Angina', 'not_preferred'],
  ['minizide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['minoxidil', 'High Blood Pressure, Angina', 'not_preferred'],
  ['mirapex', 'Parkinson\'s Disease', 'graded'],
  ['mirtazepine', 'Depression', 'allow'],
  ['mithramycin', 'Paget\'s Disease', 'graded'],
  ['moban', 'Psychotic Disorders', 'graded'],
  ['mobic', 'Osteoarthritis', 'allow'],
  ['mobidin', 'Arthritis', 'allow'],
  ['modafinil', 'Narcolepsy', 'graded'],
  ['moderil', 'High Blood Pressure, Angina', 'not_preferred'],
  ['moduretic', 'High Blood Pressure, Angina', 'not_preferred'],
  ['molindone', 'Psychotic Disorders', 'graded'],
  ['mono-gesic', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['monoket', 'High Blood Pressure, Angina', 'not_preferred'],
  ['monopril', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['moricizine', 'Arrhythmia', 'not_preferred'],
  ['morphine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['motrin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['mudrane', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['mykrox', 'High Blood Pressure, Angina', 'not_preferred'],
  ['myochrysine', 'Arthritis', 'allow'],
  ['myolin', 'Parkinson\'s Disease', 'graded'],
  ['myotrophin', 'ALS, Lou Gehrig\'s Disease', 'graded'],
  ['mysoline', 'Epilepsy, Seizure', 'not_preferred'],
  ['nabumetone', 'Rheumatoid Arthritis, Back pain, Joint Pain', 'not_preferred'],
  ['nadolol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['naldecon', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['nalfon', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['namenda', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['naprelan', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['naprosyn', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['naproxen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['naqua', 'High Blood Pressure, Angina', 'not_preferred'],
  ['naquival', 'High Blood Pressure, Angina', 'not_preferred'],
  ['nardil', 'Depression', 'allow'],
  ['naturetin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['navane', 'Psychotic Disorders', 'graded'],
  ['nedocromil', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['nefazodone', 'Depression', 'allow'],
  ['neomycin', 'High Cholesterol', 'allow'],
  ['neosar', 'Immunosuppressant, Cancer', 'graded'],
  ['neostigmine', 'Myasthenia Gravis', 'graded'],
  ['neptazane', 'Epilepsy, Seizure', 'not_preferred'],
  ['nervine', 'Rheumatoid Arthritis', 'not_preferred'],
  ['nesiritide', 'Congestive Heart Failure', 'graded'],
  ['neurontin', 'Epilepsy, Seizure, Neuropathy, Back Pain, Joint Pain', 'not_preferred'],
  ['nexium', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['niacin', 'High Cholesterol', 'allow'],
  ['niacin-lovastatin', 'High Cholesterol', 'allow'],
  ['niacor', 'High Cholesterol', 'allow'],
  ['niaspan', 'High Cholesterol', 'allow'],
  ['nicolar', 'High Cholesterol', 'allow'],
  ['nicotinic', 'Acid High Cholesterol', 'allow'],
  ['nifedipine', 'High Blood Pressure, Angina', 'not_preferred'],
  ['nilandron', 'Prostate Cancer', 'graded'],
  ['niloric', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['nilutamide', 'Prostate Cancer', 'graded'],
  ['nipride', 'Angina', 'graded'],
  ['nitro', 'Td Patch-A Angina', 'graded'],
  ['nitrobid', 'Angina', 'graded'],
  ['nitro-bid', 'Angina', 'graded'],
  ['nitrodisc', 'Angina', 'graded'],
  ['nitro-dur', 'Angina', 'graded'],
  ['nitrodur/', 'Angina', 'graded'],
  ['nitrogard', 'Angina', 'graded'],
  ['nitroglycerin', 'Angina', 'graded'],
  ['nitroglycerine', 'Angina', 'graded'],
  ['nitroglyn', 'Angina', 'graded'],
  ['nitrol', 'Angina', 'graded'],
  ['nitrolingual', 'Angina', 'graded'],
  ['nitropress', 'Angina', 'graded'],
  ['nitrospan', 'Angina', 'graded'],
  ['nitrostat', 'Angina', 'graded'],
  ['nolvadex', 'Cancer', 'graded'],
  ['norgesic', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['norisodrine', 'Aerotrol Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['normodyne', 'High Blood Pressure, Angina', 'not_preferred'],
  ['norpace', 'Arrhythmia', 'allow'],
  ['norpramin', 'Depression', 'allow'],
  ['nortriptyline', 'Depression', 'allow'],
  ['norvasc', 'High Blood Pressure, Angina', 'not_preferred'],
  ['novolin', '70/30 Insulin Dependent Diabetes Mellitus', 'not_preferred'],
  ['novophenytoin', 'Arrhythmia', 'allow'],
  ['ntg', 'Angina', 'graded'],
  ['nuprin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['ogen', 'Hormone Replacement Therapy (HRT)', 'allow'],
  ['olanzapine', 'Psychotic Disorders', 'graded'],
  ['omeprazole', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['orap', 'Tourette\'s Syndrome', 'graded'],
  ['oretic', 'High Blood Pressure, Angina', 'not_preferred'],
  ['oreticyl', 'High Blood Pressure, Angina', 'not_preferred'],
  ['orinase', 'Diabetes Mellitus', 'not_preferred'],
  ['orudis', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['oruvail', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['oxazepam', 'Anxiety', 'allow'],
  ['oxcarbazepine', 'Epilepsy, Seizure', 'not_preferred'],
  ['oxtriphylline', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['oxycodone', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['oxycontin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['pacerone', 'Ventricular Arrhythmia', 'graded'],
  ['pamelor', 'Depression', 'allow'],
  ['pancrease', 'Pancreatic Insufficiency', 'graded'],
  ['pancreatin', 'Pancreatic Insufficiency', 'graded'],
  ['pancrelipase', 'Pancreatic Insufficiency', 'graded'],
  ['papaverine', 'High Blood Pressure, Angina', 'not_preferred'],
  ['paramethadione', 'Convulsions, Epilepsy', 'not_preferred'],
  ['paramethasone', 'Oral Steroid', 'not_preferred'],
  ['parlodel', 'Parkinson\'s Disease', 'graded'],
  ['parnate', 'Depression', 'allow'],
  ['paroxetine', 'Depression, Anxiety', 'allow'],
  ['parsidol', 'Parkinson\'s Disease', 'graded'],
  ['pavabid', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pavacot', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pavagen', 'High Blood Pressure, Angina', 'not_preferred'],
  ['paxil', 'Depression', 'allow'],
  ['pediapred', 'Oral Steroid', 'allow'],
  ['penicillamine', 'Arthritis', 'allow'],
  ['pentaerythritol', 'Tetranitrate Angina', 'graded'],
  ['pentasa', 'Ulcerative Colitis', 'allow'],
  ['pentazocine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['pentoxifylline', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pentritol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pepcid', 'Peptic Ulcer Disease', 'allow'],
  ['peptic', 'Ulcer Disease Irritable Bowel Syndrome', 'allow'],
  ['perbuterol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['percocet', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['percodan', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['pergolide', 'Parkinson\'s Disease', 'graded'],
  ['peritrate', 'High Blood Pressure, Angina', 'not_preferred'],
  ['permax', 'Parkinson\'s Disease', 'graded'],
  ['permitil', 'Psychotic Disorders', 'graded'],
  ['perphenazine', 'Psychotic Disorders', 'graded'],
  ['persantine', 'High Blood Pressure, Arrhythmia, Angina, TIA, Valve Replacement', 'not_preferred'],
  ['pertofrane', 'Depression', 'allow'],
  ['phenazopyridine', 'Urinary Tract Infection', 'allow'],
  ['phenelzine', 'Depression', 'allow'],
  ['phenobarbital', 'Epilepsy, Seizure', 'allow'],
  ['phenothiazine', 'Psychotic Disorders', 'graded'],
  ['phenytoin', 'Epilepsy, Seizure', 'allow'],
  ['phyllocontin', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['pilostat', 'Glaucoma', 'allow'],
  ['pimozide', 'Schizophrenia', 'graded'],
  ['pindolol', 'High Blood Pressure, Angina', 'not_preferred'],
  ['piperacetazine', 'Psychotic Disorders', 'graded'],
  ['pirbuterol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['piroxicam', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['placidyl', 'Anxiety', 'allow'],
  ['plaquenil', 'Scleroderma, Rheumatoid Arthritis', 'not_preferred'],
  ['plavix', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['plendil', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pletal', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['polythiazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ponstel', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['posicor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pramipexole', 'Parkinson\'s Disease', 'graded'],
  ['pramlintide', 'Insulin Dependent Diabetes Mellitus', 'graded'],
  ['prandin', 'Diabetes Mellitus', 'not_preferred'],
  ['pravachol', 'High Cholesterol', 'allow'],
  ['pravastatin', 'High Cholesterol', 'allow'],
  ['prazepam', 'Anxiety', 'allow'],
  ['prazosin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['precose', 'Diabetes Mellitus', 'not_preferred'],
  ['prednicen', 'Oral Steroid', 'allow'],
  ['prednisolone', 'Oral / Injectable Steroid', 'not_preferred'],
  ['prednisone', '(10mg or less/day) Oral Steroid', 'allow'],
  ['prelone', 'Oral Steroid', 'allow'],
  ['premarin', 'Hormone Replacement Therapy (HRT)', 'allow'],
  ['prempro', 'Menopause', 'allow'],
  ['prevacid', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['prilosec', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['primacor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['primadone', 'Seizure, Epilepsy', 'not_preferred'],
  ['primidone', 'Epilepsy, Seizure', 'not_preferred'],
  ['prinivil', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['prinzide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['priscoline', 'High Blood Pressure, Angina', 'not_preferred'],
  ['pro-banthine', 'Colitis, Peptic Ulcer', 'allow'],
  ['probenecid', 'Gout', 'allow'],
  ['probucol', 'High Cholesterol', 'allow'],
  ['procainamide', 'Arrhythmia', 'graded'],
  ['procan', 'Arrhythmia', 'graded'],
  ['procardia', 'High Blood Pressure, Angina', 'not_preferred'],
  ['prochlorperazine', 'Psychotic Disorders', 'graded'],
  ['procrit', 'Kidney Failure', 'graded'],
  ['procyclidine', 'Parkinson\'s Disease', 'graded'],
  ['proketazine', 'Psychotic Disorders', 'graded'],
  ['prolixin', 'Psychotic Disorders', 'graded'],
  ['promazine', 'Psychosis', 'graded'],
  ['pronestyl', 'Arrhythmia', 'graded'],
  ['propacet', '100 Back, Hip, Joint Disorders, Arthritis', 'graded'],
  ['propafenone', 'Arrhythmia', 'allow'],
  ['propantheline', 'Colitis, Peptic Ulcer', 'allow'],
  ['propoxyphene', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['propranolol', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['proscar', 'Benign Prostatic Hyperplasia (BPH)', 'allow'],
  ['prostigmin', 'Myasthenia Gravis', 'graded'],
  ['protonix', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['protriptyline', 'Depression', 'allow'],
  ['proventil', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['prozac', 'Depression', 'allow'],
  ['pulmicort', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['pyridostigmine', 'Myasthenia Gravis', 'graded'],
  ['quaalude', 'Anxiety', 'allow'],
  ['quazepam', 'Anxiety', 'allow'],
  ['questran', 'High Cholesterol', 'allow'],
  ['quetiapine', 'Fumarate Psychotic Disorders', 'graded'],
  ['quibron-t/sr', 'Asthma, Bronchitis, Emphysema, COPD', 'allow'],
  ['quinaglute', 'Dura Arrhythmia', 'allow'],
  ['quinapril', 'High Blood Pressure', 'allow'],
  ['quinethazone', 'High Blood Pressure, Angina', 'allow'],
  ['quinidex', 'Arrhythmia', 'graded'],
  ['quinidine', 'Arrhythmia', 'graded'],
  ['quinora', 'Arrhythmia', 'graded'],
  ['rabeprazole', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['raloxifene', 'Osteoporosis', 'allow'],
  ['ramipril', 'High Blood Pressure', 'allow'],
  ['ranitidine', 'Gastritis, Gastroesophageal Reflux, Peptic Ulcer', 'allow'],
  ['raudixin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['rauzide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['regitine', 'High Blood Pressure, Angina', 'not_preferred'],
  ['reglan', 'Gastroesophageal Reflux (GERD)', 'allow'],
  ['regranex', 'Diabetic Ulcers', 'graded'],
  ['regroton', 'High Blood Pressure, Angina', 'not_preferred'],
  ['relafen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['remeron', 'Depression', 'allow'],
  ['remicade', 'Rheumatoid Arthritis', 'graded'],
  ['reminyl', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['renese', 'High Blood Pressure, Angina', 'not_preferred'],
  ['repaglinide', 'Diabetes Mellitus', 'not_preferred'],
  ['repoise', 'Psychotic Disorders', 'graded'],
  ['requip', 'Parkinson\'s Disease', 'graded'],
  ['reserpine', 'High Blood Pressure, Angina', 'not_preferred'],
  ['respbid', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['rezulin', 'Diabetes Mellitus', 'graded'],
  ['rheopro', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['rheumatrex', 'Lupus, Scleroderma, Leukemia, Lymphoma, Rheumatoid Arthritis', 'graded'],
  ['rhinocort', 'Asthma', 'allow'],
  ['ridaura', 'Rheumatoid Arthritis', 'graded'],
  ['riluzole', 'ALS, Lou Gehrig\'s Disease', 'graded'],
  ['risperdal', 'Psychotic Disorders', 'graded'],
  ['risperidone', 'Psychotic Disorders', 'graded'],
  ['ritalin', 'Depression', 'allow'],
  ['rituxan', 'Non-Hodgkin\'s Lymphoma', 'graded'],
  ['rituximab', 'Recurrent Non-Hodgkin\'s Disease', 'graded'],
  ['ropinerole', 'Parkinson\'s Disease', 'graded'],
  ['rowasa', 'Ulcerative Colitis', 'allow'],
  ['rufin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['rythmol', 'Arrhythmia', 'allow'],
  ['sabril', 'Seizure, Epilepsy', 'not_preferred'],
  ['salbutamol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['salflex', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['salicylsalicylic', 'Acid(ASA) Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['salmeterol', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['salmon', 'Calcitonin Osteoporosis', 'allow'],
  ['salsalate', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['saluron', 'High Blood Pressure, Angina', 'not_preferred'],
  ['salutensin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['sandimmune', 'Lupus, Scleroderma, Cancer, Organ Transplant', 'graded'],
  ['sansert', 'Headaches', 'allow'],
  ['sarafem', 'Depression, Obsessive-Compulsive Disorder', 'allow'],
  ['sectral', 'Arrhythmia', 'allow'],
  ['selegiline', 'Parkinson\'s Disease', 'graded'],
  ['ser-ap-es', 'High Blood Pressure, Angina', 'not_preferred'],
  ['serax', 'Anxiety', 'allow'],
  ['serentil', 'Psychotic Disorders', 'graded'],
  ['serevent', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['serlect', 'Schizophrenia', 'graded'],
  ['seroquel', 'Psychotic Disorders', 'graded'],
  ['serpasil', 'High Blood Pressure, Angina', 'not_preferred'],
  ['sertindole', 'Schizophrenia', 'graded'],
  ['sertraline', 'Depression, Anxiety, Obsessive-Compulsive Disorders', 'allow'],
  ['serzone', 'Depression', 'allow'],
  ['simvastatin', 'High Cholesterol', 'allow'],
  ['sinemet', 'Restless Leg Syndrome, Parkinson\'s Disease', 'not_preferred'],
  ['sinequan', 'Depression', 'allow'],
  ['skelaxin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['slo-bid', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['slo-phyllin', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['slow', 'Fe Anemia', 'allow'],
  ['sodium', 'Salicylate Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['solganal', 'Rheumatoid Arthritis', 'graded'],
  ['solu-cortef', 'Injectable Steroid', 'graded'],
  ['solu-medrol', 'Injectable Steroid', 'graded'],
  ['soma', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['somophyllin', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['sorbitrate', 'High Blood Pressure, Angina', 'not_preferred'],
  ['sparine', 'Psychosis', 'graded'],
  ['spironolactone', 'High Blood Pressure, Angina', 'not_preferred'],
  ['stalevo', 'Parkinson\'s Disease', 'graded'],
  ['stelazine', 'Psychotic Disorders', 'graded'],
  ['sucralfate', 'Gastritis, Gastroesophageal Reflux, Peptic Ulcer', 'allow'],
  ['sular', 'High Blood Pressure, Angina', 'not_preferred'],
  ['sulfasalazine', 'Regional Enteritis, Ulcerative Colitis', 'allow'],
  ['sulfinpyrazone', 'Gout', 'allow'],
  ['sumatriptan', 'Headaches', 'allow'],
  ['suprofen', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['surmontil', 'Depression', 'allow'],
  ['sustaire', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['symbyax', 'Psychotic Disorders', 'graded'],
  ['symmetrel', 'Parkinson\'s Disease', 'graded'],
  ['synophylate', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['syn-rx', 'Thyroid Disorder', 'allow'],
  ['synthroid', 'Thyroid Disorder', 'allow'],
  ['tacrine', 'Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['tagamet', 'Colitis, Peptic Ulcer', 'allow'],
  ['talwin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['tambocor', 'Arrhythmia', 'graded'],
  ['tamoxifen', 'Cancer', 'graded'],
  ['tamsulosin', 'Benign Prostatic Hyperplasia (BPH)', 'allow'],
  ['tapazole', 'Thyroid Disorder', 'allow'],
  ['taractan', 'Psychotic Disorders', 'graded'],
  ['tarka', 'High Blood Pressure, Angina', 'allow'],
  ['tasmar', 'Parkinson\'s Disease', 'graded'],
  ['tavist', 'Asthma', 'allow'],
  ['tegretol', 'Epilepsy, Seizure, Bi-Polar Disorder', 'allow'],
  ['temazepam', 'Depression, Anxiety', 'allow'],
  ['tenex', 'High Blood Pressure, Angina', 'not_preferred'],
  ['tenoretic', 'High Blood Pressure, Angina', 'not_preferred'],
  ['tenormin', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['terazosin', 'High Blood Pressure, Benign Prostatic Hypertrophy (BPH)', 'allow'],
  ['terbutaline', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['tetracyclic', 'Psychotic Disorders', 'graded'],
  ['tetrahydroamino', 'Acridine (THA) Chronic Organic Brain Disorder, Dementia, Alzheimer\'s Disease, Memory Loss', 'graded'],
  ['thalitone', 'High Blood Pressure, Angina', 'not_preferred'],
  ['theo-24', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theobid', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theobron sr', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theocap', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theochron', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theoclear', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theo-dur', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theolair-sr', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theophyl', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theophylline', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theospan sr', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['theovent', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['thioridazine', 'Psychotic Disorders', 'graded'],
  ['thiothixene', 'Psychotic Disorders', 'graded'],
  ['thioxanthene', 'Psychotic Disorders', 'graded'],
  ['thorazine', 'Psychotic Disorders', 'graded'],
  ['tiazac', 'High Blood Pressure, Angina', 'not_preferred'],
  ['ticlid', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve, Disease, Stroke, TIA', 'graded'],
  ['ticlopadine', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['ticlopidine', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['tilade', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['timolide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['timolol', 'Glaucoma', 'allow'],
  ['timoptic', 'Glaucoma', 'allow'],
  ['tindal', 'Psychotic Disorders', 'graded'],
  ['tirofiban', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['tizanidine', 'HCL Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['tocainide', 'Arrhythmia', 'not_preferred'],
  ['tofranil', 'Depression', 'allow'],
  ['tolazamide', 'Diabetes Mellitus', 'not_preferred'],
  ['tolbutamide', 'Diabetes Mellitus', 'not_preferred'],
  ['tolcapone', 'Parkinson\'s Disease', 'graded'],
  ['tolectin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['tolinase', 'Diabetes Mellitus', 'not_preferred'],
  ['tolmetin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['tonocard', 'Arrhythmia', 'not_preferred'],
  ['topamax', 'Epilepsy, Seizure', 'not_preferred'],
  ['topiramate', 'Epilepsy, Seizure', 'not_preferred'],
  ['toprol', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['toradol', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['tornalate', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['tramadol', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['trandate', 'High Blood Pressure, Angina', 'not_preferred'],
  ['transderm-nitro', 'High Blood Pressure, Angina', 'graded'],
  ['tranxene', 'Anxiety', 'allow'],
  ['tranylcypromine', 'Depression', 'allow'],
  ['trazodone', 'Depression', 'allow'],
  ['trendar', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['trental', 'High Blood Pressure, Angina', 'not_preferred'],
  ['triamcinolone', 'Oral / Injectable /Inhaled Steroid, Emphysema, COPD', 'not_preferred'],
  ['triamterene', 'High Blood Pressure, Angina', 'not_preferred'],
  ['triavil', 'Depression, Anxiety', 'allow'],
  ['triazolam', 'Depression, Anxiety', 'allow'],
  ['trichlormethiazide', 'High Blood Pressure, Angina', 'not_preferred'],
  ['tridil', 'High Blood Pressure, Angina', 'not_preferred'],
  ['tridione', 'Seizure, Epilepsy', 'not_preferred'],
  ['trifluoperazine', 'Psychotic Disorders', 'graded'],
  ['triflupromazine', 'Psychotic Disorders', 'graded'],
  ['trihexphenidyl', 'Tremor, Parkinson\'s Disease', 'not_preferred'],
  ['trilafon', 'Psychotic Disorders', 'graded'],
  ['trilisate', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['trimethadione', 'Seizure, Epilepsy', 'not_preferred'],
  ['trimipramine', 'Depression', 'allow'],
  ['troglitazone', 'Diabetes Mellitus', 'graded'],
  ['truvada', 'HIV Prevention, HIV treatment', 'allow'],
  ['tylox', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['ultram', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['uni-dur', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['uniphyl', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['unipres', 'High Blood Pressure', 'allow'],
  ['uniretic', 'High Blood Pressure, Angina', 'not_preferred'],
  ['unithroid', 'Thyroid Disorder', 'allow'],
  ['univasc', 'High Blood Pressure, Angina', 'not_preferred'],
  ['urodol', 'Urinary Tract Infection', 'allow'],
  ['ursodeoxycholic', 'Acid Gallstones', 'allow'],
  ['valium', 'Anxiety', 'allow'],
  ['valproate', 'Epilepsy, Seizure', 'not_preferred'],
  ['valrelease', 'Anxiety', 'allow'],
  ['valsartan', 'High Blood Pressure', 'allow'],
  ['vanceril', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['vascor', 'High Blood Pressure, Angina', 'not_preferred'],
  ['vaseretic', 'High Blood Pressure, Angina', 'not_preferred'],
  ['vasodilan', 'High Blood Pressure, Angina', 'not_preferred'],
  ['vasotec', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['vasoxyl', 'Arrhythmia', 'allow'],
  ['venlafaxine', 'Depression', 'allow'],
  ['ventolin', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['verapamil', 'Arrhythmia, Angina, High Blood Pressure', 'not_preferred'],
  ['verelan', 'High Blood Pressure, Angina', 'not_preferred'],
  ['vesprin', 'Psychotic Disorders', 'graded'],
  ['vicodin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['viokase', 'Pancreatic Insufficiency', 'graded'],
  ['vioxx', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['visken', 'High Blood Pressure, Angina', 'not_preferred'],
  ['vistaril', 'Anxiety', 'allow'],
  ['vivabatrin', 'Seizure, Epilepsy', 'not_preferred'],
  ['vivactil', 'Depression', 'allow'],
  ['volmax', 'Asthma, Bronchitis, Emphysema, COPD', 'not_preferred'],
  ['voltaren', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['vytorin', 'High Cholesterol', 'allow'],
  ['warfarin', 'Arrhythmia, CAD, Embolism, Heart Attack, Heart Condition, Heart Valve Disease, Stroke, TIA', 'graded'],
  ['welchol', 'High Cholesterol', 'allow'],
  ['wellbutrin', 'Depression, Smoking Cessation', 'allow'],
  ['wigraine', 'Headaches', 'allow'],
  ['wytensin', 'High Blood Pressure, Angina', 'not_preferred'],
  ['xalatan', 'Glaucoma', 'allow'],
  ['xanax', 'Anxiety', 'allow'],
  ['xopenex', 'Asthma', 'allow'],
  ['xylocaine', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['zantac', 'Gastritis, Gastroesophageal Reflux, Peptic Ulcer', 'allow'],
  ['zarontin', 'Epilepsy, Seizure', 'not_preferred'],
  ['zaroxolyn', 'High Blood Pressure, Angina', 'not_preferred'],
  ['zebeta', 'High Blood Pressure, Angina', 'not_preferred'],
  ['zestoretic', 'High Blood Pressure, Angina', 'not_preferred'],
  ['zestril', 'High Blood Pressure, Arrhythmia, Angina', 'not_preferred'],
  ['zetia', 'High Cholesterol', 'allow'],
  ['ziac', 'High Blood Pressure, Angina', 'not_preferred'],
  ['zocor', 'High Cholesterol', 'allow'],
  ['zoladex', 'Prostate Cancer, Cancer', 'graded'],
  ['zoloft', 'Depression', 'allow'],
  ['zomig', 'Migraine Headache', 'allow'],
  ['zorprin', 'Back, Hip, Joint Disorders, Arthritis', 'allow'],
  ['zyloprim', 'Gout', 'allow'],
  ['zyprexa', 'Psychotic Mental Disorders,Schizophrenia', 'graded'],
  ['graded', 'Benefit Graded Benefit', 'graded'],
  ['acquired', 'IMMUNE DEFICIENCY SYNDROME-AIDS', 'graded'],
  ['acromegaly', '', 'graded'],
  ['addisons', 'DISEASE', 'graded'],
  ['aids', 'RELATED COMPLEX-ARC', 'graded'],
  ['alcoholism/alcohol', 'ABUSE', 'graded'],
  ['alzheimers', 'DISEASE', 'graded'],
  ['amyotrophic', 'LATERAL SCLEROSIS Lou Gehrig Disease', 'graded'],
  ['angina', '(chest pain caused by blocked heart artery)', 'graded'],
  ['autism', '', 'graded'],
  ['barrett\'s', 'ESOPHAGUS', 'graded'],
  ['bipolar', 'DISORDER (extreme feelings of high and low)', 'graded'],
  ['bone', 'MARROW TRANSPLANT', 'graded'],
  ['bronchiectasis', '', 'graded'],
  ['buergers', 'DISEASE', 'graded'],
  ['if', 'currently under treatment postpose. Graded Benefit', 'graded'],
  ['cardiomyopathy', '', 'graded'],
  ['cerebral', 'PALSY', 'graded'],
  ['atrial', 'FIBRILLATION (irregular heart beat)', 'graded'],
  ['chronic', 'OBSTRUCTIVE LUNG DISEASE/ Graded Benefit Graded Benefit', 'graded'],
  ['cirrhosis', 'OF THE LIVER/LIVER FAILURE', 'graded'],
  ['colostomy/ileostomy', '', 'graded'],
  ['cystic', 'FIBROSIS', 'graded'],
  ['decubitus', 'ULCERS', 'graded'],
  ['deep', 'VEIN THROMBOSIS', 'graded'],
  ['defibrillator', 'IMPLANT', 'graded'],
  ['dementia', '', 'graded'],
  ['diabetic', 'ULCERS', 'graded'],
  ['dialysis', '', 'graded'],
  ['downs', 'SYNDROME Graded Benefit Graded Benefit', 'graded'],
  ['drug/chemical', 'DEPENDENCY Graded Benefit Graded Benefit', 'graded'],
  ['edema', 'Graded Benefit Graded Benefit', 'graded'],
  ['emphysema', '', 'graded'],
  ['end', 'STAGE RENAL DISEASE', 'graded'],
  ['enteritis', '(not Crohn s disease)', 'graded'],
  ['esophageal', 'VARICES', 'graded'],
  ['gaucher\'s', 'DISEASE', 'graded'],
  ['heart', 'ATTACK (blood flow to the heart is interrupted)', 'graded'],
  ['hemochromatosis', '(body stores large amounts of iron)', 'graded'],
  ['hemophilia', '', 'graded'],
  ['hiv', 'POSITIVE STATUS Sub Standard', 'graded'],
  ['hodgkin\'s', 'DISEASE (see cancer)', 'graded'],
  ['huntington\'s', 'CHOREA', 'graded'],
  ['hyperparathyroidism', '', 'graded'],
  ['kidney', 'DIALYSIS', 'graded'],
  ['leukemia', '', 'graded'],
  ['liver', 'TRANSPLANT', 'graded'],
  ['lung', 'TRANSPLANT', 'graded'],
  ['lymphoma', '(see cancer)', 'graded'],
  ['manic', 'DEPRESSION', 'graded'],
  ['melanoma', '(malignant skin cancer) (See cancer)', 'graded'],
  ['memory', 'LOSS', 'graded'],
  ['mitral', 'VALVE STENOSIS', 'graded'],
  ['multiple', 'MYELOMA', 'graded'],
  ['muscular', 'DYSTROPHY', 'graded'],
  ['myasthenia', 'GRAVIS', 'graded'],
  ['myeloma', '', 'graded'],
  ['myocardial', 'INFARCTION', 'graded'],
  ['narcolepsy', '', 'graded'],
  ['neurogenic', 'BLADDER', 'graded'],
  ['non', 'HODGKINS DISEASE (lymphatic system cancer)', 'graded'],
  ['benefit', '', 'graded'],
  ['organ', 'TRANSPLANT RECIPIENT', 'graded'],
  ['oxygen', 'USAGE', 'graded'],
  ['pacemaker', 'IMPLANT', 'graded'],
  ['pancreatic', 'INSUFFICIENCY', 'graded'],
  ['paralysis', '', 'graded'],
  ['parkinson\'s', 'DISEASE', 'graded'],
  ['physical', 'THERAPY', 'graded'],
  ['pituitary', 'GLAND DISORDER', 'graded'],
  ['pregnancy', '', 'graded'],
  ['raynaud\'s', 'DISEASE', 'graded'],
  ['renal', 'INSUFFICIENCY', 'graded'],
  ['sarcoidosis', 'Graded Benefit Graded Benefit', 'graded'],
  ['schizophrenia', '', 'graded'],
  ['scleroderma', '', 'graded'],
  ['social', 'SECURITY DISABILITY INSURANCE', 'graded'],
  ['spina', 'BIFIDA', 'graded'],
  ['status', 'ASTHMATICUS', 'graded'],
  ['stroke', '(blood supply to the brain has been interrupted)', 'graded'],
  ['thrombocytopenia', '(low platelet count in the blood)', 'graded'],
  ['tourette\'s', 'SYNDROME', 'graded'],
  ['ulcerative', 'ESOPHAGUS', 'graded'],
  ['weight', 'LOSS Graded Benefit Graded Benefit', 'graded'],
];
